import React, { createContext, useContext, useState, useEffect } from 'react';
import { I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type LanguageCode = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => Promise<void>;
  t: (key: string) => string;
  isRTL: boolean;
}

// Global hookless bindings for monkey-patched elements (Text, Alert, TextInput)
export let globalT: (key: string) => string = (key) => key;
export let globalIsRTL = false;

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav & Headers
    Home: 'Home',
    Events: 'Events',
    Reels: 'Reels',
    Profile: 'Profile',
    Welcome: 'Welcome',
    Recipes: 'Recipes',
    Map: 'Map',
    'Patient Resources': 'Patient Resources',
    Notifications: 'Notifications',
    Settings: 'Settings',
    'Edit Profile': 'Edit Profile',
    'Add Event': 'Add Event',
    Community: 'Community',

    // Section Labels
    ACCOUNT: 'ACCOUNT',
    NOTIFICATIONS: 'NOTIFICATIONS',
    APPEARANCE: 'APPEARANCE',
    SUPPORT: 'SUPPORT',

    // Setting Items & Subtitles
    EDIT_PROFILE: 'Edit Profile',
    EDIT_PROFILE_SUB: 'Update your name, photo & info',
    CHANGE_PASSWORD: 'Change Password',
    CHANGE_PASSWORD_SUB: 'Update your login credentials',
    PUSH_NOTIFS: 'Push Notifications',
    PUSH_NOTIFS_SUB: 'Alerts, reminders and updates',
    EMAIL_UPDATES: 'Email Updates',
    EMAIL_UPDATES_SUB: 'Weekly digest and newsletters',
    DARK_MODE: 'Dark Mode',
    DARK_MODE_SUB: 'Switch to dark theme',
    TEXT_SIZE: 'Text Size',
    LANGUAGE: 'Language',
    LANGUAGE_SUB: 'Choose your preferred language',
    HELP_CENTER: 'Help Center',
    HELP_CENTER_SUB: 'FAQs and guides',
    REPORT_BUG: 'Report a Bug',
    REPORT_BUG_SUB: 'Help us improve the app',

    // General Actions & Dialogs
    LOGOUT: 'Log Out',
    CLOSE: 'Close',
    CANCEL: 'Cancel',
    SUBMIT: 'Submit',
    SAVE: 'Save',
    SUCCESS: 'Success',
    ERROR: 'Error',
    'Log out': 'Log out',
    'Privacy & Security': 'Privacy & Security',

    // Welcome Screen
    'Salut , Bienvenue!': 'Hello, Welcome!',
    'Connectez-vous\npour continuer': 'Log in\nto continue',
    'Se connecter': 'Log In',
    'Creer un compte': 'Create Account',

    // Auth Screens
    Login: 'Login',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    'GET STARTED': 'GET STARTED',
    'Full Name': 'Full Name',
    'Enter your name': 'Enter your name',
    Email: 'Email',
    'Enter your email': 'Enter your email',
    Password: 'Password',
    'Enter your password': 'Enter your password',
    'Create a password': 'Create a password',
    'Confirm Password': 'Confirm Password',
    'Re-enter your password': 'Re-enter your password',
    'Forgot Password?': 'Forgot Password?',
    'Already Account? ': 'Already have an account? ',
    'No Account? ': "Don't have an account? ",
    Register: 'Register',
    'Profile Type': 'Profile Type',
    'Min 8 chars · one uppercase · one number': 'Min 8 chars · one uppercase · one number',
    Celiac: 'Celiac',
    Proche: 'Relative',
    'Pro Commerce': 'Pro Commerce',
    'Pro Health': 'Pro Health',

    // Form errors
    'Email is required': 'Email is required',
    'Invalid email': 'Invalid email',
    'Password is required': 'Password is required',
    'Full name must be at least 2 characters': 'Full name must be at least 2 characters',
    'Valid email is required': 'Valid email is required',
    'Password must be at least 8 characters': 'Password must be at least 8 characters',
    'Must contain an uppercase letter': 'Must contain an uppercase letter',
    'Must contain a number': 'Must contain a number',
    'Passwords do not match': 'Passwords do not match',
    'Please select a profile type': 'Please select a profile type',

    // Change Password Modal
    CURRENT_PASSWORD: 'Current Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm New Password',
    ENTER_CURRENT_PWD: 'Enter current password',
    ENTER_NEW_PWD: 'Enter new password',
    CONFIRM_NEW_PWD: 'Confirm new password',
    REQ_FIELDS: 'All fields are required.',
    PWD_LENGTH: 'New password must be at least 6 characters.',
    PWD_MATCH: 'New passwords do not match.',
    PWD_SUCCESS: 'Password updated successfully! ✅',
    PWD_FAIL: 'Failed to change password. Please verify current password.',

    // Report Bug Modal
    BUG_TITLE: 'Bug Title',
    BUG_DESC: 'Bug Description',
    SEVERITY: 'Severity',
    SUBMIT_REPORT: 'Submit Report',
    THANK_YOU: 'Thank you! ✅',
    BUG_SUBMITTED: 'Your report has been submitted.',
    LOW: 'Low',
    MEDIUM: 'Medium',
    HIGH: 'High',
    FIELDS_REQ: 'Fields Required',
    ENTER_BUG_DETAILS: 'Please enter a bug title and description.',
    SUBMIT_ERROR: 'Submission Error',
    BUG_FAIL_TEXT: 'Failed to report bug. Please try again.',
    BUG_TITLE_PLACEHOLDER: 'e.g. App crashes on search',
    BUG_DESC_PLACEHOLDER: 'Tell us what went wrong...',

    // Text Size Modal
    SMALL: 'Small',
    MEDIUM_SIZE: 'Medium',
    LARGE: 'Large',

    // Language Modal
    SELECT_LANGUAGE: 'Select Language',
    ENGLISH: 'English',
    FRENCH: 'French',
    ARABIC: 'Arabic',

    // FAQs
    FAQ_Q1: 'How do I know a product is gluten-free?',
    FAQ_A1: 'All products displayed on GlUnity are certified gluten-free by our partner sellers. Look for the "GF" badge on the product list, or check the recommended status of the bakery itself.',
    FAQ_Q2: 'How can I contact a seller?',
    FAQ_A2: 'You can tap on the "View Seller" button on the product details page to view their profile, where you can call them directly or send a message.',
    FAQ_Q3: 'What is a Glutenia-recommended bakery?',
    FAQ_A3: 'It is a bakery verified by our medical and food safety teams to ensure 100% cross-contamination-free production, safe for celiacs.',
    FAQ_Q4: 'How do I change my language preferences?',
    FAQ_A4: 'You can update your language in the Settings page under the Support section.',

    // Home Screen Text
    'Instantly Check for Gluten & Find Safe Alternatives': 'Instantly Check for Gluten & Find Safe Alternatives',
    'Tap to Scan': 'Tap to Scan',
    'Quick Access': 'Quick Access',
    'Check recipes': 'Check recipes',
    'Check Events': 'Check Events',
    'See All': 'See All',
    'Find Products': 'Find Products',
    'Search products, recipes, events': 'Search products, recipes, events',
    'Gluten-Free Recipes': 'Gluten-Free Recipes',
    'Healthy and nutritious food recipes': 'Healthy and nutritious food recipes',
    'Popular recipes': 'Popular recipes',
    Popular: 'Popular',
    recipes: 'recipes',

    // Recipes & details
    Ingredients: 'Ingredients',
    Steps: 'Steps',
    Nutrition: 'Nutrition',
    Calories: 'Calories',
    Carbs: 'Carbs',
    Protein: 'Protein',

    // Events Screen Text
    All: 'All',
    Meetups: 'Meetups',
    Classes: 'Classes',
    Markets: 'Markets',
    'Aucun événement à afficher.': 'No events to display.',

    // Patient Resources
    Categories: 'Categories',
    Featured: 'Featured',
    'All ressources': 'All resources',
    'Videos & Sessions': 'Videos & Sessions',
    'No resources found': 'No resources found',
    'Read more': 'Read more',
    'Read more →': 'Read more →',
    'min read': 'min read',
    min: 'min',
    'This content is for informational purposes only and does not replace professional medical advice. Always consult a healthcare provider.': 'This content is for informational purposes only and does not replace professional medical advice. Always consult a healthcare provider.',
    'Celiac\nDisease': 'Celiac\nDisease',
    'Diet Basics': 'Diet Basics',
    'Safe Foods\n& Risks': 'Safe Foods\n& Risks',
    'Lifestyle\nTips': 'Lifestyle\nTips',

    // Profile Screen
    'Your Role': 'Your Role',
    'Your Journey': 'Your Journey',
    'Every action makes the ecosystem stronger.': 'Every action makes the ecosystem stronger.',
    Beginner: 'Beginner',
    Aware: 'Aware',
    'Safe Eater': 'Safe Eater',
    Fighter: 'Fighter',
    Titan: 'Titan',
    'Gluten-Free Warrior': 'Gluten-Free Warrior',
    'Living gluten-free for 12 years 🌿': 'Living gluten-free for 12 years 🌿',
    'You actively manage your gluten-free lifestyle and inspire others.': 'You actively manage your gluten-free lifestyle and inspire others.',

    // Mock Data Translates
    'Gluten-Free Pizza': 'Gluten-Free Pizza',
    'Homemade GF crust topped with fresh mozzarella and basil.': 'Homemade GF crust topped with fresh mozzarella and basil.',
    'Tunisian Brik': 'Tunisian Brik',
    'Crispy gluten-free pastry filled with egg, tuna, and parsley.': 'Crispy gluten-free pastry filled with egg, tuna, and parsley.',
    'Quinoa Salad': 'Quinoa Salad',
    'Refreshing salad with quinoa, cucumber, tomatoes, and lemon dressing.': 'Refreshing salad with quinoa, cucumber, tomatoes, and lemon dressing.',
    'Protein GF Pancakes': 'Protein GF Pancakes',
    'Healthy Quinoa Bowl': 'Healthy Quinoa Bowl',
    'Celiac Disease Basics': 'Celiac Disease Basics',
    'How to Avoid Cross-Contamination': 'How to Avoid Cross-Contamination',
    'Gluten-Free Flour Guide': 'Gluten-Free Flour Guide',
    'Handling Social Dining': 'Handling Social Dining',
    'Celiac Disease: What Is It?': 'Celiac Disease: What Is It?',
    'How to Safely Eat Out': 'How to Safely Eat Out',
    'Hidden Gluten in Everyday Foods': 'Hidden Gluten in Everyday Foods',
    'Glutenia recommended': 'Glutenia recommended',
    'Verifié par l\'association': 'Verified by the association',
    'Gluten-Free cooking class': 'Gluten-Free cooking class',
    'Celiac Association Meetup': 'Celiac Association Meetup',
    'Gluten-Free Food Market': 'Gluten-Free Food Market',
    // Events
    'View on Map': 'View on Map',
    'people going': 'people going',
    'About Event': 'About Event',
    'No description provided.': 'No description provided.',
    'Price': 'Price',
    'Free': 'Free',
    'Join Event': 'Join Event',
    'Cancel': 'Cancel',
    'Loading...': 'Loading...',
    'Cancel participation': 'Cancel participation',
    'Are you sure you want to cancel your participation? This will remove you from the attendee list.': 'Are you sure you want to cancel your participation? This will remove you from the attendee list.',
    'Keep': 'Keep',
    // Add Event Screen
    'Organize Event': 'Organize Event',
    'Event Title *': 'Event Title *',
    'Starts At *': 'Starts At *',
    'Venue Name': 'Venue Name',
    'Street Address': 'Street Address',
    'City': 'City',
    'Country': 'Country',
    'Max Capacity': 'Max Capacity',
    'Price (TND)': 'Price (TND)',
    'About the Event': 'About the Event',
    'Create Event': 'Create Event',
    'Add Cover Photo': 'Add Cover Photo',
    'Recommend landscape 16:9 ratio': 'Recommend landscape 16:9 ratio',
    'e.g. Gluten-Free Cooking Workshop': 'e.g. Gluten-Free Cooking Workshop',
    'Discard draft?': 'Discard draft?',
    'You have unsaved changes. Are you sure you want to discard them and leave?': 'You have unsaved changes. Are you sure you want to discard them and leave?',
    'Keep Editing': 'Keep Editing',
    'Discard': 'Discard',
    'Event Created!': 'Event Created!',
    'Your gluten-free event is now published and visible to the community.': 'Your gluten-free event is now published and visible to the community.',
    'Go to Calendar': 'Go to Calendar',
    // Seller Journey & Info
    'Learner': 'Learner',
    'Supporter': 'Supporter',
    'Advocate': 'Advocate',
    'Champion': 'Champion',
    'Guardian': 'Guardian',
    'Gluten-Free Ally': 'Gluten-Free Ally',
    'You support and help someone living gluten-free.': 'You support and help someone living gluten-free.',
    'My products': 'My products',
    'Visibility': 'Visibility',
    'Clients messages': 'Clients messages',
    // Alerts/Notifications Screen
    'Mark all': 'Mark all',
    'All caught up! 🌿': 'All caught up! 🌿',
    'No new notifications at the moment.': 'No new notifications at the moment.',
    // Notification list dynamic text
    'Welcome to GlUnity! 🌾': 'Welcome to GlUnity! 🌾',
    'Find certified gluten-free products, local events, and recipes tailored to your lifestyle.': 'Find certified gluten-free products, local events, and recipes tailored to your lifestyle.',
    'Gluten-Free Cooking Workshop 🥞': 'Gluten-Free Cooking Workshop 🥞',
    'A new event was published: Pancake Sunday Meetup on June 15th! RSVP to book your spot.': 'A new event was published: Pancake Sunday Meetup on June 15th! RSVP to book your spot.',
    'Pure Treats Bakery 🥐': 'Pure Treats Bakery 🥐',
    'Senda added fresh gluten-free chocolate croissants to the products market catalog.': 'Senda added fresh gluten-free chocolate croissants to the products market catalog.',
    'Community Verified Badge Alert 🛡️': 'Community Verified Badge Alert 🛡️',
    'Your profile has been verified as a Gluten-Free Warrior! Enjoy our certified badges.': 'Your profile has been verified as a Gluten-Free Warrior! Enjoy our certified badges.',
    // Stats & Seller Dashboard
    'Last 7 days': 'Last 7 days',
    'Last 30 days': 'Last 30 days',
    'Your visibility': 'Your visibility',
    'Views': 'Views',
    'This month': 'This month',
    'Reviews': 'Reviews',
    'Average rating': 'Average rating',
    'Map clicks': 'Map clicks',
    'Visits generated': 'Visits generated',
    'Products': 'Products',
    'Listed items': 'Listed items',
    'Views over time': 'Views over time',
    'Insights': 'Insights',
    'Your most viewed product': 'Your most viewed product',
    'Almond Croissant': 'Almond Croissant',
    'Top user interaction day': 'Top user interaction day',
    'Saturday (Peak at 11 AM)': 'Saturday (Peak at 11 AM)',
    'Mon': 'Mon',
    'Wed': 'Wed',
    'Fri': 'Fri',
    'Sun': 'Sun',
    // Event Categories & Details
    'Meetup': 'Meetup',
    'Class': 'Class',
    'Webinar': 'Webinar',
    'Market': 'Market',
    'Other': 'Other',
    // Seller Profile Screen Additional
    '100% Gluten-Free Bakery': '100% Gluten-Free Bakery',
    'Recommended by Glutenia': 'Recommended by Glutenia',
    'Verified safe establishment': 'Verified safe establishment',
    '2.4 km away': '2.4 km away',
    'Open today • 08:00 - 19:00': 'Open today • 08:00 - 19:00',
    'Follow': 'Follow',
    'Message': 'Message',
    'Edit Info': 'Edit Info',
    'Add': 'Add',
    'Product': 'Product',
    'Dashboard': 'Dashboard',
    'Bakery Menu': 'Bakery Menu',
    'See all': 'See all',
    'No products in the menu yet.': 'No products in the menu yet.',
    'Recent Reviews': 'Recent Reviews',
    'The gluten-free croissants are absolutely wonderful! Best bakery in Tunis.': 'The gluten-free croissants are absolutely wonderful! Best bakery in Tunis.',
    "100% safe for celiac. Their bread doesn't crumble at all! Highly recommend.": "100% safe for celiac. Their bread doesn't crumble at all! Highly recommend.",
    'Very tasty treats and friendly staff. Love the Tunis branch.': 'Very tasty treats and friendly staff. Love the Tunis branch.',
    '2 hours ago': '2 hours ago',
    'Yesterday': 'Yesterday',
    '3 days ago': '3 days ago',
    // Product Market Screen
    'Gluten free products': 'Gluten free products',
    'homemade': 'homemade',
    'Certified': 'Certified',
    'No products found': 'No products found',
    'Try a different filter or check back later.': 'Try a different filter or check back later.',
    // Recipes Screen
    'Gluten-Free Recipes': 'Gluten-Free Recipes',
    'Healthy and nutritious food recipes': 'Healthy and nutritious food recipes',
    'Popular': 'Popular',
    'recipes': 'recipes',
    'Tunisian': 'Tunisian',
    'Easy': 'Easy',
    'Quick': 'Quick',
    // Customer Profile Screen
    'Gluten-Free Warrior': 'Gluten-Free Warrior',
    'Living gluten-free for 12 years 🌿': 'Living gluten-free for 12 years 🌿',
    'Your Role': 'Your Role',
    'You actively manage your gluten-free lifestyle and inspire others.': 'You actively manage your gluten-free lifestyle and inspire others.',
    'Your Journey': 'Your Journey',
    'Beginner': 'Beginner',
    'Aware': 'Aware',
    'Safe Eater': 'Safe Eater',
    'Fighter': 'Fighter',
    'Titan': 'Titan',
    'Every action makes the ecosystem stronger.': 'Every action makes the ecosystem stronger.',
    'Privacy & Security': 'Privacy & Security',
    'Log out': 'Log out',

    // Map Screen
    'Filter places': 'Filter places',
    'Category': 'Category',
    'Status': 'Status',
    'Certified only': 'Certified only',
    'Gluten-free only': 'Gluten-free only',
    'Clear filters': 'Clear filters',
    'Get in Touch': 'Get in Touch',
    'No phone number listed': 'No phone number listed',
    'Copied!': 'Copied!',
    'Copy Number': 'Copy Number',
    'Call Now': 'Call Now',
    Restaurants: 'Restaurants',
    Bakeries: 'Bakeries',
    Grocery: 'Grocery',
    'Cafés': 'Cafés',
    Pharmacy: 'Pharmacy',

    // Events search & empty state
    'Search events...': 'Search events...',
    'No events to display.': 'No events to display.',

    // BottomNavBar accessibility
    'Scan for gluten': 'Scan for gluten',

    // Header greeting
    Welcome: 'Welcome',

    // Seller profile customer actions
    'Event Type': 'Event Type',
    'Event title is required.': 'Event title is required.',
    'Date format is required (e.g. YYYY-MM-DD).': 'Date format is required (e.g. YYYY-MM-DD).',
    'Location Details': 'Location Details',
    'e.g. Green Bakery': 'e.g. Green Bakery',
    'e.g. 15 Avenue de Paris': 'e.g. 15 Avenue de Paris',
    'Tunis': 'Tunis',
    'Tunisia': 'Tunisia',
    'About the event': 'About the event',

    // Seller Pro Profile (menu items)
    'My products': 'My products',
    'Clients messages': 'Clients messages',
    Visibility: 'Visibility',

    // Intro / Onboarding
    'Scannez Vos': 'Scan Your',
    'Aliments': 'Food',
    "Scannez rapidement les produits pour vérifier s'ils sont sans gluten et sûrs.": "Quickly scan barcodes to instantly verify if products are gluten-free and safe for your diet.",
    'Trouvez Des': 'Find Safe',
    'Lieux Sûrs': 'Places',
    'Découvrez les restaurants, boulangeries et magasins proposant des options sans gluten près de chez vous.': 'Discover certified restaurants, bakeries, and local grocery stores with reliable gluten-free options.',
    'Rejoignez La': 'Join The',
    'Communauté': 'Community',
    "Partagez des recettes, des conseils et des expériences avec d'autres personnes vivant sans gluten.": "Share recipes, read articles, ask questions, and connect with other celiac warriors nearby.",

    // Welcome / Auth Screens
    'Salut , Bienvenue!': 'Welcome Back!',
    'Connectez-vous\npour continuer': 'Log in to\ncontinue',
    'Se connecter': 'Log In',
    'Creer un compte': 'Create Account',
    'Login': 'Login',
    'Email': 'Email',
    'Enter your email': 'Enter your email',
    'Password': 'Password',
    'Enter your password': 'Enter your password',
    'Forgot Password?': 'Forgot Password?',
    'LOGIN': 'LOGIN',
    'No Account? ': 'No Account? ',
    'Register': 'Register',
    'Email is required': 'Email is required',
    'Invalid email': 'Invalid email',
    'Password is required': 'Password is required',
    'GET STARTED': 'GET STARTED',
    'Full Name': 'Full Name',
    'Enter your name': 'Enter your name',
    'Create a password': 'Create a password',
    'Confirm Password': 'Confirm Password',
    'Re-enter your password': 'Re-enter your password',
    'Profile Type': 'Profile Type',
    'Celiac': 'Celiac',
    'Proche': 'Relative/Friend',
    'Pro Commerce': 'Pro Commerce',
    'Pro Health': 'Pro Health',
    'Please select a profile type': 'Please select a profile type',
    'Min 8 chars · one uppercase · one number': 'Min 8 chars · one uppercase · one number',
    'REGISTER': 'REGISTER',
    'Already Account? ': 'Already Account? ',
    'Full name must be at least 2 characters': 'Full name must be at least 2 characters',
    'Valid email is required': 'Valid email is required',
    'Password must be at least 8 characters': 'Password must be at least 8 characters',
    'Must contain an uppercase letter': 'Must contain an uppercase letter',
    'Must contain a number': 'Must contain a number',
    'Passwords do not match': 'Passwords do not match',
    'Forgot Password': 'Forgot Password',
    'Please enter a valid email address': 'Please enter a valid email address',
    'Submit': 'Submit',
    '← Back to Login': '← Back to Login',
    'Email sent to change your password': 'Email sent to change your password',
    'Back to Login': 'Back to Login',
    'Password Updated!': 'Password Updated!',
    'Your password has been reset successfully.\nYou can now log in with your new password.': 'Your password has been reset successfully.\nYou can now log in with your new password.',
    'Go to Login': 'Go to Login',
    'Link Expired': 'Link Expired',
    'This reset link has expired or was already used.\nPlease request a new one.': 'This reset link has expired or was already used.\nPlease request a new one.',
    'Request New Link': 'Request New Link',
    'Set New Password': 'Set New Password',
    'Choose a strong new password for your account.': 'Choose a strong new password for your account.',
    'New Password': 'New Password',
    'At least 8 characters': 'At least 8 characters',
    'Reset Password': 'Reset Password',
    'Minimum 8 characters': 'Minimum 8 characters',
    'Must include an uppercase letter': 'Must include an uppercase letter',
    'Must include a number': 'Must include a number',
    'Invalid or missing reset token. Please request a new link.': 'Invalid or missing reset token. Please request a new link.',
    'Reset failed. The link may have expired.': 'Reset failed. The link may have expired.',
    'Email Verified!': 'Email Verified!',
    'Your email address has been verified successfully.\nYou can now log in to your account and enjoy GlUnity.': 'Your email address has been verified successfully.\nYou can now log in to your account and enjoy GlUnity.',
    'Verification Failed': 'Verification Failed',
    'This verification link is invalid or has expired.\nPlease request a new verification email.': 'This verification link is invalid or has expired.\nPlease request a new verification email.',
    'Resend Verification': 'Resend Verification',

    // SplashScreen
    'Glutenia logo': 'GlUnity',
    'Sans Gluten, Sans probleme': 'Gluten Free, Hassle Free',

    // Product details
    'About this product': 'About this product',
    'Ingredients': 'Ingredients',
    'Price': 'Price',
    'View Seller': 'View Seller',
    '2.4 km away': '2.4 km away',
    'Open today • 08:00 - 19:00': 'Open today • 08:00 - 19:00',
    'A rustic gluten-free loaf with a crispy crust and chewy interior. Fermented for 24 hours for optimal flavor and digestion.': 'A rustic gluten-free loaf with a crispy crust and chewy interior. Fermented for 24 hours for optimal flavor and digestion.',
    'Delicate gluten-free pastry made with certified safe flours. Perfectly layered and baked to a golden finish.': 'Delicate gluten-free pastry made with certified safe flours. Perfectly layered and baked to a golden finish.',
    'Soft, fluffy gluten-free bread baked fresh every morning. Made from 100% certified gluten-free grains.': 'Soft, fluffy gluten-free bread baked fresh every morning. Made from 100% certified gluten-free grains.',
    'Premium gluten-free flour blend, perfect for home baking. Contains no traces of wheat, rye, or barley.': 'Premium gluten-free flour blend, perfect for home baking. Contains no traces of wheat, rye, or barley.',
    'Light and crunchy gluten-free snack, ideal for people with celiac disease or gluten intolerance.': 'Light and crunchy gluten-free snack, ideal for people with celiac disease or gluten intolerance.',
    'Indulgent gluten-free dessert crafted with the finest safe ingredients. Satisfying and totally wheat-free.': 'Indulgent gluten-free dessert crafted with the finest safe ingredients. Satisfying and totally wheat-free.',
    'Lovingly crafted at home using traditional recipes adapted for gluten-free diets. Made with natural ingredients.': 'Lovingly crafted at home using traditional recipes adapted for gluten-free diets. Made with natural ingredients.',
    'A premium gluten-free product crafted with certified ingredients, safe for people with celiac disease and gluten intolerance.': 'A premium gluten-free product crafted with certified ingredients, safe for people with celiac disease and gluten intolerance.',

    // Patient Resources categories
    'Celiac\nDisease': 'Celiac\nDisease',
    'Diet Basics': 'Diet Basics',
    'Safe Foods\n& Risks': 'Safe Foods\n& Risks',
    'Lifestyle\nTips': 'Lifestyle\nTips',
    'min read': 'min read',
    'min': 'min',
    'Read more': 'Read more',
    'Read more →': 'Read more →',
    'All ressources': 'All Resources',
    'No resources found': 'No resources found',
    'Videos & Sessions': 'Videos & Sessions',
    'See All': 'See All',
    'This content is for informational purposes only and does not replace professional medical advice. Always consult a healthcare provider.': 'This content is for informational purposes only and does not replace professional medical advice. Always consult a healthcare provider.',

    // Patient Resources seed articles
    'What is Celiac Disease?': 'What is Celiac Disease?',
    'A comprehensive guide to understanding celiac disease, its symptoms, diagnosis,': 'A comprehensive guide to understanding celiac disease, its symptoms, diagnosis,',
    'Celiac disease is a serious autoimmune disorder that occurs in genetically predisposed people where the ingestion of gluten leads to damage in the small intestine. Learn about symptoms, diagnosis, and living gluten-free.': 'Celiac disease is a serious autoimmune disorder that occurs in genetically predisposed people where the ingestion of gluten leads to damage in the small intestine. Learn about symptoms, diagnosis, and living gluten-free.',
    'Dr. Amira Ben Ali': 'Dr. Amira Ben Ali',
    'Starting a Gluten-Free Diet': 'Starting a Gluten-Free Diet',
    'Essential steps and practical advice for patients transitioning to a gluten-free': 'Essential steps and practical advice for patients transitioning to a gluten-free',
    'Transitioning to a gluten-free diet requires careful planning and education. This guide covers what foods to avoid, safe alternatives, and how to read labels.': 'Transitioning to a gluten-free diet requires careful planning and education. This guide covers what foods to avoid, safe alternatives, and how to read labels.',
    'Nutritionist Panel': 'Nutritionist Panel',
    'Hidden Sources of Gluten': 'Hidden Sources of Gluten',
    'Gluten hides in many unexpected products including sauces, medications, and cosmetics. Learn to identify and avoid these hidden sources to stay safe.': 'Gluten hides in many unexpected products including sauces, medications, and cosmetics. Learn to identify and avoid these hidden sources to stay safe.',
    'GlUnity Medical Team': 'GlUnity Medical Team',
    'Nutritional Deficiencies in Celiac Patients': 'Nutritional Deficiencies in Celiac Patients',
    'Celiac disease can lead to deficiencies in iron, folate, calcium, and vitamins B12 and D. This article explains how to identify and address these deficiencies.': 'Celiac disease can lead to deficiencies in iron, folate, calcium, and vitamins B12 and D. This article explains how to identify and address these deficiencies.',
    'Dining Out Safely': 'Dining Out Safely',
    'Eating out with celiac disease requires preparation and communication. This guide teaches you how to ask the right questions and choose safe restaurants.': 'Eating out with celiac disease requires preparation and communication. This guide teaches you how to ask the right questions and choose safe restaurants.',
    'Living with Celiac Disease': 'Living with Celiac Disease',
    'Gluten-Free Meal Prep': 'Gluten-Free Meal Prep',
    'by': 'by',
    'Article': 'Article',
    'Video': 'Video',

    // Map screen
    'Filter places': 'Filter places',
    'Category': 'Category',
    'Status': 'Status',
    'Certified only': 'Certified only',
    'Gluten-free only': 'Gluten-free only',
    'Clear filters': 'Clear filters',
    'Get in Touch': 'Get in Touch',
    'No phone number listed': 'No phone number listed',
    'Copied!': 'Copied!',
    'Copy Number': 'Copy Number',
    'Call Now': 'Call Now',
    'Cancel': 'Cancel',
    'Filter': 'Filter',
    'reviews': 'reviews',
    'KM': 'KM',
    'Read More': 'Read More',
    '({reviewLabel} reviews)': '({reviewLabel} reviews)',
    '{distance} km away from you': '{distance} km away from you',
    'Gluten Free': 'Gluten Free',

    // Map categories
    'All': 'All',
    'Restaurants': 'Restaurants',
    'Bakeries': 'Bakeries',
    'Grocery': 'Grocery',
    'Cafés': 'Cafés',
    'Pharmacy': 'Pharmacy',

    // Map seed locations
    'Ben Yaghlane Shops': 'Ben Yaghlane Shops',
    'Premium Tunisian grocery known for high-end gluten-free pasta, breads and gourmet products.': 'Premium Tunisian grocery known for high-end gluten-free pasta, breads and gourmet products.',
    'Avenue Habib Bourguiba': 'Avenue Habib Bourguiba',
    'Tunis': 'Tunis',
    'La Maison Sans Gluten': 'La Maison Sans Gluten',
    'Dedicated 100% gluten-free bakery with fresh breads and pastries daily.': 'Dedicated 100% gluten-free bakery with fresh breads and pastries daily.',
    '14 Rue de Marseille': '14 Rue de Marseille',
    'Green Leaf Café': 'Green Leaf Café',
    'Cozy café offering certified gluten-free brunch, salads and smoothies.': 'Cozy café offering certified gluten-free brunch, salads and smoothies.',
    'Avenue Mohamed V': 'Avenue Mohamed V',
    'Pasta Verde': 'Pasta Verde',
    'Italian restaurant with a separate gluten-free kitchen line.': 'Italian restaurant with a separate gluten-free kitchen line.',
    '5 Rue de Carthage': '5 Rue de Carthage',
    'Carrefour Marsa': 'Carrefour Marsa',
    'Supermarket with a wide selection of gluten-free products. Some shared shelves — check labels.': 'Supermarket with a wide selection of gluten-free products. Some shared shelves — check labels.',
    'La Marsa': 'La Marsa',
    'Pharmacie Centrale': 'Pharmacie Centrale',
    'Stocks specialized gluten-free dietary supplements and medical-grade products.': 'Stocks specialized gluten-free dietary supplements and medical-grade products.',
    'Rue Charles de Gaulle': 'Rue Charles de Gaulle',
  },
  fr: {
    // Nav & Headers
    Home: 'Accueil',
    Events: 'Événements',
    Reels: 'Réels',
    Profile: 'Profil',
    Welcome: 'Bienvenue',
    Recipes: 'Recettes',
    Map: 'Carte',
    'Patient Resources': 'Ressources Patient',
    Notifications: 'Notifications',
    Settings: 'Paramètres',
    'Edit Profile': 'Modifier le profil',
    'Add Event': 'Ajouter un événement',
    Community: 'Communauté',

    // Section Labels
    ACCOUNT: 'COMPTE',
    NOTIFICATIONS: 'NOTIFICATIONS',
    APPEARANCE: 'APPARENCE',
    SUPPORT: 'SUPPORT',

    // Setting Items & Subtitles
    EDIT_PROFILE: 'Modifier le Profil',
    EDIT_PROFILE_SUB: 'Mettre à jour votre nom, photo et infos',
    CHANGE_PASSWORD: 'Changer le mot de passe',
    CHANGE_PASSWORD_SUB: 'Mettre à jour vos identifiants',
    PUSH_NOTIFS: 'Notifications Push',
    PUSH_NOTIFS_SUB: 'Alertes, rappels et mises à jour',
    EMAIL_UPDATES: 'Mises à jour par e-mail',
    EMAIL_UPDATES_SUB: 'Résumé hebdomadaire et newsletters',
    DARK_MODE: 'Mode Sombre',
    DARK_MODE_SUB: 'Passer au thème sombre',
    TEXT_SIZE: 'Taille du texte',
    LANGUAGE: 'Langue',
    LANGUAGE_SUB: 'Choisissez votre langue préférée',
    HELP_CENTER: "Centre d'aide",
    HELP_CENTER_SUB: 'FAQs et guides',
    REPORT_BUG: 'Signaler un bug',
    REPORT_BUG_SUB: "Aidez-nous à améliorer l'application",

    // General Actions & Dialogs
    LOGOUT: 'Se déconnecter',
    CLOSE: 'Fermer',
    CANCEL: 'Annuler',
    SUBMIT: 'Soumettre',
    SAVE: 'Enregistrer',
    SUCCESS: 'Succès',
    ERROR: 'Erreur',
    'Log out': 'Se déconnecter',
    'Privacy & Security': 'Confidentialité et sécurité',

    // Welcome Screen
    'Salut , Bienvenue!': 'Salut, Bienvenue !',
    'Connectez-vous\npour continuer': 'Connectez-vous\npour continuer',
    'Se connecter': 'Se connecter',
    'Creer un compte': 'Créer un compte',

    // Auth Screens
    Login: 'Connexion',
    LOGIN: 'CONNEXION',
    REGISTER: 'S\'INSCRIRE',
    'GET STARTED': 'COMMENCER',
    'Full Name': 'Nom complet',
    'Enter your name': 'Entrez votre nom',
    Email: 'E-mail',
    'Enter your email': 'Entrez votre e-mail',
    Password: 'Mot de passe',
    'Enter your password': 'Entrez votre mot de passe',
    'Create a password': 'Créez un mot de passe',
    'Confirm Password': 'Confirmer le mot de passe',
    'Re-enter your password': 'Réécrivez votre mot de passe',
    'Forgot Password?': 'Mot de passe oublié ?',
    'Already Account? ': 'Déjà un compte ? ',
    'No Account? ': 'Pas de compte ? ',
    Register: 'S\'inscrire',
    'Profile Type': 'Type de profil',
    'Min 8 chars · one uppercase · one number': 'Min. 8 caractères · une majuscule · un chiffre',
    Celiac: 'Cœliaque',
    Proche: 'Proche',
    'Pro Commerce': 'Pro Commerce',
    'Pro Health': 'Pro Santé',

    // Form errors
    'Email is required': 'E-mail requis',
    'Invalid email': 'E-mail invalide',
    'Password is required': 'Mot de passe requis',
    'Full name must be at least 2 characters': 'Le nom complet doit comporter au moins 2 caractères',
    'Valid email is required': 'Un e-mail valide est requis',
    'Password must be at least 8 characters': 'Le mot de passe doit comporter au moins 8 caractères',
    'Must contain an uppercase letter': 'Doit contenir une lettre majuscule',
    'Must contain a number': 'Doit contenir un chiffre',
    'Passwords do not match': 'Les mots de passe ne correspondent pas',
    'Please select a profile type': 'Veuillez sélectionner un type de profil',

    // Change Password Modal
    CURRENT_PASSWORD: 'Mot de passe actuel',
    NEW_PASSWORD: 'Nouveau mot de passe',
    CONFIRM_PASSWORD: 'Confirmer le nouveau mot de passe',
    ENTER_CURRENT_PWD: 'Saisir le mot de passe actuel',
    ENTER_NEW_PWD: 'Saisir le nouveau mot de passe',
    CONFIRM_NEW_PWD: 'Confirmer le nouveau mot de passe',
    REQ_FIELDS: 'Tous les champs sont requis.',
    PWD_LENGTH: 'Le nouveau mot de passe doit comporter au moins 6 caractères.',
    PWD_MATCH: 'Les nouveaux mots de passe ne correspondent pas.',
    PWD_SUCCESS: 'Mot de passe mis à jour avec succès ! ✅',
    PWD_FAIL: 'Échec de la modification du mot de passe. Veuillez vérifier le mot de passe actuel.',

    // Report Bug Modal
    BUG_TITLE: 'Titre du bug',
    BUG_DESC: 'Description du bug',
    SEVERITY: 'Gravité',
    SUBMIT_REPORT: 'Soumettre le rapport',
    THANK_YOU: 'Merci ! ✅',
    BUG_SUBMITTED: 'Votre rapport a été soumis.',
    LOW: 'Faible',
    MEDIUM: 'Moyen',
    HIGH: 'Élevé',
    FIELDS_REQ: 'Champs requis',
    ENTER_BUG_DETAILS: 'Veuillez entrer un titre et une description pour le bug.',
    SUBMIT_ERROR: 'Erreur de soumission',
    BUG_FAIL_TEXT: 'Échec du signalement du bug. Veuillez réessayer.',
    BUG_TITLE_PLACEHOLDER: 'ex. L\'application plante lors de la recherche',
    BUG_DESC_PLACEHOLDER: 'Dites-nous ce qui n\'a pas fonctionné...',

    // Text Size Modal
    SMALL: 'Petit',
    MEDIUM_SIZE: 'Moyen',
    LARGE: 'Grand',

    // Language Modal
    SELECT_LANGUAGE: 'Sélectionner la langue',
    ENGLISH: 'Anglais',
    FRENCH: 'Français',
    ARABIC: 'Arabe',

    // FAQs
    FAQ_Q1: 'Comment savoir si un produit est sans gluten ?',
    FAQ_A1: 'Tous les produits affichés sur GlUnity sont certifiés sans gluten par nos vendeurs partenaires. Recherchez le badge "GF" sur la liste des produits, ou vérifiez le statut recommandé de la boulangerie elle-même.',
    FAQ_Q2: 'Comment puis-je contacter un vendeur ?',
    FAQ_A2: 'Vous pouvez appuyer sur le bouton "Voir le vendeur" sur la page des détails du produit pour voir son profil, où vous pouvez l\'appeler directement ou envoyer un message.',
    FAQ_Q3: 'Qu\'est-ce qu\'une boulangerie recommandée par Glutenia ?',
    FAQ_A3: 'Il s\'agit d\'une boulangerie vérifiée par nos équipes médicales et de sécurité alimentaire pour garantir une production 100% sans contamination croisée, sûre pour les coeliaques.',
    FAQ_Q4: 'Comment changer mes préférences de langue ?',
    FAQ_A4: 'Vous pouvez mettre à jour votre langue dans la page des Paramètres sous la section Support.',

    // Home Screen Text
    'Instantly Check for Gluten & Find Safe Alternatives': 'Vérifiez le gluten & trouvez des alternatives sûres',
    'Tap to Scan': 'Appuyer pour scanner',
    'Quick Access': 'Accès rapide',
    'Check recipes': 'Voir les recettes',
    'Check Events': 'Voir les événements',
    'See All': 'Voir tout',
    'Find Products': 'Trouver des produits',
    'Search products, recipes, events': 'Rechercher produits, recettes, événements',
    'Gluten-Free Recipes': 'Recettes sans gluten',
    'Healthy and nutritious food recipes': 'Recettes saines et nutritives',
    'Popular recipes': 'Recettes populaires',
    Popular: 'Populaire',
    recipes: 'recettes',

    // Recipes & details
    Ingredients: 'Ingrédients',
    Steps: 'Étapes',
    Nutrition: 'Valeurs nutritionnelles',
    Calories: 'Calories',
    Carbs: 'Glucides',
    Protein: 'Protéines',

    // Events Screen Text
    All: 'Tout',
    Meetups: 'Rencontres',
    Classes: 'Cours',
    Markets: 'Marchés',
    'Aucun événement à afficher.': 'Aucun événement à afficher.',

    // Patient Resources
    Categories: 'Catégories',
    Featured: 'À la une',
    'All ressources': 'Toutes les ressources',
    'Videos & Sessions': 'Vidéos & sessions',
    'No resources found': 'Aucune ressource trouvée',
    'Read more': 'Lire la suite',
    'Read more →': 'Lire la suite →',
    'min read': 'min de lecture',
    min: 'min',
    'This content is for informational purposes only and does not replace professional medical advice. Always consult a healthcare provider.': 'Ce contenu est à titre informatif uniquement et ne remplace pas un avis médical professionnel. Consultez toujours un médecin.',
    'Celiac\nDisease': 'Maladie\nCœliaque',
    'Diet Basics': 'Bases de\nl\'alimentation',
    'Safe Foods\n& Risks': 'Aliments Sûrs\n& Risques',
    'Lifestyle\nTips': 'Conseils de\nMode de Vie',

    // Profile Screen
    'Your Role': 'Votre rôle',
    'Your Journey': 'Votre parcours',
    'Every action makes the ecosystem stronger.': 'Chaque action renforce l\'écosystème.',
    Beginner: 'Débutant',
    Aware: 'Sensibilisé',
    'Safe Eater': 'Mangeur sûr',
    Fighter: 'Combattant',
    Titan: 'Titan',
    'Gluten-Free Warrior': 'Guerrier sans gluten',
    'Living gluten-free for 12 years 🌿': 'Vit sans gluten depuis 12 ans 🌿',
    'You actively manage your gluten-free lifestyle and inspire others.': 'Vous gérez activement votre mode de vie sans gluten et inspirez les autres.',

    // Mock Data Translates
    'Gluten-Free Pizza': 'Pizza sans gluten',
    'Homemade GF crust topped with fresh mozzarella and basil.': 'Pâte maison sans gluten garnie de mozzarella fraîche et de basilic.',
    'Tunisian Brik': 'Brik tunisien',
    'Crispy gluten-free pastry filled with egg, tuna, and parsley.': 'Feuille de brik croustillante sans gluten farcie d\'œuf, de thon et de persil.',
    'Quinoa Salad': 'Salade de quinoa',
    'Refreshing salad with quinoa, cucumber, tomatoes, and lemon dressing.': 'Salade rafraîchissante de quinoa, concombre, tomates et sauce au citron.',
    'Protein GF Pancakes': 'Pancakes protéinés sans gluten',
    'Healthy Quinoa Bowl': 'Bol de quinoa sain',
    'Celiac Disease Basics': 'Bases de la maladie cœliaque',
    'How to Avoid Cross-Contamination': 'Comment éviter la contamination croisée',
    'Gluten-Free Flour Guide': 'Guide des farines sans gluten',
    'Handling Social Dining': 'Gérer les repas en société',
    'Celiac Disease: What Is It?': 'Maladie cœliaque : Qu\'est-ce que c\'est ?',
    'How to Safely Eat Out': 'Comment manger dehors en toute sécurité',
    'Hidden Gluten in Everyday Foods': 'Gluten caché dans les aliments du quotidien',
    'Glutenia recommended': 'Recommandé par Glutenia',
    'Verifié par l\'association': 'Vérifié par l\'association',
    'Gluten-Free cooking class': 'Cours de cuisine sans gluten',
    'Celiac Association Meetup': 'Rencontre de l\'association cœliaque',
    'Gluten-Free Food Market': 'Marché alimentaire sans gluten',
    // Events
    'View on Map': 'Voir sur la carte',
    'people going': 'personnes y vont',
    'About Event': 'À propos de l\'événement',
    'No description provided.': 'Aucune description fournie.',
    'Price': 'Prix',
    'Free': 'Gratuit',
    'Join Event': 'Rejoindre l\'événement',
    'Cancel': 'Annuler',
    'Loading...': 'Chargement...',
    'Cancel participation': 'Annuler la participation',
    'Are you sure you want to cancel your participation? This will remove you from the attendee list.': 'Êtes-vous sûr de vouloir annuler votre participation ? Cela vous retirera de la liste des participants.',
    'Keep': 'Conserver',
    // Add Event Screen
    'Organize Event': 'Organiser un événement',
    'Event Title *': 'Titre de l\'événement *',
    'Starts At *': 'Commence le *',
    'Venue Name': 'Nom du lieu',
    'Street Address': 'Adresse',
    'City': 'Ville',
    'Country': 'Pays',
    'Max Capacity': 'Capacité maximale',
    'Price (TND)': 'Prix (TND)',
    'About the Event': 'À propos de l\'événement',
    'Create Event': 'Créer l\'événement',
    'Add Cover Photo': 'Ajouter une photo de couverture',
    'Recommend landscape 16:9 ratio': 'Format paysage recommandé 16:9',
    'e.g. Gluten-Free Cooking Workshop': 'ex. Atelier de cuisine sans gluten',
    'Discard draft?': 'Abandonner le brouillon ?',
    'You have unsaved changes. Are you sure you want to discard them and leave?': 'Vous avez des modifications non enregistrées. Êtes-vous sûr de vouloir les abandonner et quitter ?',
    'Keep Editing': 'Continuer l\'édition',
    'Discard': 'Abandonner',
    'Event Created!': 'Événement créé !',
    'Your gluten-free event is now published and visible to the community.': 'Votre événement sans gluten est maintenant publié et visible par la communauté.',
    'Go to Calendar': 'Aller au calendrier',
    // Seller Journey & Info
    'Learner': 'Apprenti',
    'Supporter': 'Soutien',
    'Advocate': 'Défenseur',
    'Champion': 'Champion',
    'Guardian': 'Gardien',
    'Gluten-Free Ally': 'Allié Sans Gluten',
    'You support and help someone living gluten-free.': 'Vous soutenez et aidez une personne vivant sans gluten.',
    'My products': 'Mes produits',
    'Visibility': 'Visibilité',
    'Clients messages': 'Messages des clients',
    // Alerts/Notifications Screen
    'Mark all': 'Tout marquer',
    'All caught up! 🌿': 'Tout est à jour ! 🌿',
    'No new notifications at the moment.': 'Aucune nouvelle notification pour le moment.',
    // Notification list dynamic text
    'Welcome to GlUnity! 🌾': 'Bienvenue sur GlUnity ! 🌾',
    'Find certified gluten-free products, local events, and recipes tailored to your lifestyle.': 'Trouvez des produits certifiés sans gluten, des événements locaux et des recettes adaptées à votre mode de vie.',
    'Gluten-Free Cooking Workshop 🥞': 'Atelier de cuisine sans gluten 🥞',
    'A new event was published: Pancake Sunday Meetup on June 15th! RSVP to book your spot.': 'Un nouvel événement a été publié : Pancake Sunday Meetup le 15 juin ! Réservez votre place.',
    'Pure Treats Bakery 🥐': 'Boulangerie Pure Treats 🥐',
    'Senda added fresh gluten-free chocolate croissants to the products market catalog.': 'Senda a ajouté des croissants au chocolat frais sans gluten au catalogue du marché.',
    'Community Verified Badge Alert 🛡️': 'Alerte Badge Vérifié de la Communauté 🛡️',
    'Your profile has been verified as a Gluten-Free Warrior! Enjoy our certified badges.': 'Votre profil a été vérifié en tant que Guerrier sans gluten ! Profitez de nos badges certifiés.',
    // Stats & Seller Dashboard
    'Last 7 days': 'Les 7 derniers jours',
    'Last 30 days': 'Les 30 derniers jours',
    'Your visibility': 'Votre visibilité',
    'Views': 'Vues',
    'This month': 'Ce mois-ci',
    'Reviews': 'Avis',
    'Average rating': 'Note moyenne',
    'Map clicks': 'Clics sur la carte',
    'Visits generated': 'Visites générées',
    'Products': 'Produits',
    'Listed items': 'Articles répertoriés',
    'Views over time': 'Vues au fil du temps',
    'Insights': 'Analyses',
    'Your most viewed product': 'Votre produit le plus vu',
    'Almond Croissant': 'Croissant aux amandes',
    'Top user interaction day': 'Journée de pointe',
    'Saturday (Peak at 11 AM)': 'Samedi (Pic à 11h)',
    'Mon': 'Lun',
    'Wed': 'Mer',
    'Fri': 'Ven',
    'Sun': 'Dim',
    // Event Categories & Details
    'Meetup': 'Rencontre',
    'Class': 'Cours',
    'Webinar': 'Webinaire',
    'Market': 'Marché',
    'Other': 'Autre',
    // Seller Profile Screen Additional
    '100% Gluten-Free Bakery': 'Boulangerie 100% sans gluten',
    'Recommended by Glutenia': 'Recommandé par Glutenia',
    'Verified safe establishment': 'Établissement certifié sûr',
    '2.4 km away': 'à 2,4 km',
    'Open today • 08:00 - 19:00': 'Ouvert aujourd\'hui • 08h00 - 19h00',
    'Follow': 'Suivre',
    'Message': 'Message',
    'Edit Info': 'Modifier les infos',
    'Add': 'Ajouter',
    'Product': 'Produit',
    'Dashboard': 'Tableau de bord',
    'Bakery Menu': 'Menu Boulangerie',
    'See all': 'Voir tout',
    'No products in the menu yet.': 'Aucun produit dans le menu pour le moment.',
    'Recent Reviews': 'Avis Récents',
    'The gluten-free croissants are absolutely wonderful! Best bakery in Tunis.': 'Les croissants sans gluten sont absolument magnifiques ! Meilleure boulangerie de Tunis.',
    "100% safe for celiac. Their bread doesn't crumble at all! Highly recommend.": '100% sûr pour les cœliaques. Leur pain ne s\'effrite pas du tout ! Je recommande vivement.',
    'Very tasty treats and friendly staff. Love the Tunis branch.': 'Des gourmandises très savoureuses et un personnel amical. J\'adore la succursale de Tunis.',
    '2 hours ago': 'Il y a 2 heures',
    'Yesterday': 'Hier',
    '3 days ago': 'Il y a 3 jours',
    // Product Market Screen
    'Gluten free products': 'Produits sans gluten',
    'homemade': 'Fait maison',
    'Certified': 'Certifié',
    'No products found': 'Aucun produit trouvé',
    'Try a different filter or check back later.': 'Essayez un autre filtre ou revenez plus tard.',
    // Recipes Screen
    'Gluten-Free Recipes': 'Recettes sans gluten',
    'Healthy and nutritious food recipes': 'Recettes saines et nutritives',
    'Popular': 'Populaire',
    'recipes': 'recettes',
    'Tunisian': 'Tunisien',
    'Easy': 'Facile',
    'Quick': 'Rapide',
    // Customer Profile Screen
    'Gluten-Free Warrior': 'Guerrier sans gluten',
    'Living gluten-free for 12 years 🌿': 'Vivant sans gluten depuis 12 ans 🌿',
    'Your Role': 'Votre Rôle',
    'You actively manage your gluten-free lifestyle and inspire others.': 'Vous gérez activement votre mode de vie sans gluten et inspirez les autres.',
    'Your Journey': 'Votre Parcours',
    'Beginner': 'Débutant',
    'Aware': 'Sensibilisé',
    'Safe Eater': 'Mangeur Sûr',
    'Fighter': 'Combattant',
    'Titan': 'Titan',
    'Every action makes the ecosystem stronger.': "Chaque action renforce l'écosystème.",
    'Privacy & Security': 'Confidentialité et sécurité',
    'Log out': 'Se déconnecter',

    // Map Screen FR
    'Filter places': 'Filtrer les lieux',
    'Category': 'Catégorie',
    'Status': 'Statut',
    'Certified only': 'Certifiés uniquement',
    'Gluten-free only': 'Sans gluten uniquement',
    'Clear filters': 'Effacer les filtres',
    'Get in Touch': 'Nous contacter',
    'No phone number listed': 'Aucun numéro de téléphone renseigné',
    'Copied!': 'Copié !',
    'Copy Number': 'Copier le numéro',
    'Call Now': 'Appeler maintenant',
    Restaurants: 'Restaurants',
    Bakeries: 'Boulangeries',
    Grocery: 'Épicerie',
    'Cafés': 'Cafés',
    Pharmacy: 'Pharmacie',

    // Events search & empty state
    'Search events...': 'Rechercher des événements...',
    'No events to display.': 'Aucun événement à afficher.',

    // BottomNavBar accessibility
    'Scan for gluten': 'Scanner le gluten',

    // Add Event extra fields
    'Event Type': 'Type d\'événement',
    'Event title is required.': 'Le titre de l\'événement est requis.',
    'Date format is required (e.g. YYYY-MM-DD).': 'Le format de date est requis (ex. AAAA-MM-JJ).',
    'Location Details': 'Détails du lieu',
    'e.g. Green Bakery': 'ex. Boulangerie Verte',
    'e.g. 15 Avenue de Paris': 'ex. 15 Avenue de Paris',
    'Tunis': 'Tunis',
    'Tunisia': 'Tunisie',
    'About the event': 'À propos de l\'événement',

    // Seller Pro Profile (menu items)
    'My products': 'Mes produits',
    'Clients messages': 'Messages clients',
    Visibility: 'Visibilité',

    // Intro / Onboarding
    'Scannez Vos': 'Scannez Vos',
    'Aliments': 'Aliments',
    "Scannez rapidement les produits pour vérifier s'ils sont sans gluten et sûrs.": "Scannez rapidement les produits pour vérifier s'ils sont sans gluten et sûrs.",
    'Trouvez Des': 'Trouvez Des',
    'Lieux Sûrs': 'Lieux Sûrs',
    'Découvrez les restaurants, boulangeries et magasins proposant des options sans gluten près de chez vous.': 'Découvrez les restaurants, boulangeries et magasins proposant des options sans gluten près de chez vous.',
    'Rejoignez La': 'Rejoignez La',
    'Communauté': 'Communauté',
    "Partagez des recettes, des conseils et des expériences avec d'autres personnes vivant sans gluten.": "Partagez des recettes, des conseils et des expériences avec d'autres personnes vivant sans gluten.",

    // Welcome / Auth Screens
    'Salut , Bienvenue!': 'Salut, Bienvenue !',
    'Connectez-vous\npour continuer': 'Connectez-vous\npour continuer',
    'Se connecter': 'Se connecter',
    'Creer un compte': 'Créer un compte',
    'Login': 'Connexion',
    'Email': 'E-mail',
    'Enter your email': 'Entrez votre e-mail',
    'Password': 'Mot de passe',
    'Enter your password': 'Entrez votre mot de passe',
    'Forgot Password?': 'Mot de passe oublié ?',
    'LOGIN': 'SE CONNECTER',
    'No Account? ': 'Pas de compte ? ',
    'Register': 'S\'inscrire',
    'Email is required': 'L\'adresse e-mail est requise',
    'Invalid email': 'E-mail invalide',
    'Password is required': 'Le mot de passe est requis',
    'GET STARTED': 'COMMENCER',
    'Full Name': 'Nom complet',
    'Enter your name': 'Entrez votre nom',
    'Create a password': 'Créer un mot de passe',
    'Confirm Password': 'Confirmer le mot de passe',
    'Re-enter your password': 'Réentrez votre mot de passe',
    'Profile Type': 'Type de profil',
    'Celiac': 'Cœliaque',
    'Proche': 'Proche',
    'Pro Commerce': 'Pro Commerce',
    'Pro Health': 'Pro Santé',
    'Please select a profile type': 'Veuillez sélectionner un type de profil',
    'Min 8 chars · one uppercase · one number': 'Min 8 caractères · une majuscule · un chiffre',
    'REGISTER': 'S\'INSCRIRE',
    'Already Account? ': 'Déjà un compte ? ',
    'Full name must be at least 2 characters': 'Le nom complet doit comporter au moins 2 caractères',
    'Valid email is required': 'Un e-mail valide est requis',
    'Password must be at least 8 characters': 'Le mot de passe doit comporter au moins 8 caractères',
    'Must contain an uppercase letter': 'Doit contenir une lettre majuscule',
    'Must contain a number': 'Doit contenir un chiffre',
    'Passwords do not match': 'Les mots de passe ne correspondent pas',
    'Forgot Password': 'Mot de passe oublié',
    'Please enter a valid email address': 'Veuillez entrer une adresse e-mail valide',
    'Submit': 'Envoyer',
    '← Back to Login': '← Retour à la connexion',
    'Email sent to change your password': 'E-mail envoyé pour changer votre mot de passe',
    'Back to Login': 'Retour à la connexion',
    'Password Updated!': 'Mot de passe mis à jour !',
    'Your password has been reset successfully.\nYou can now log in with your new password.': 'Votre mot de passe a été réinitialisé avec succès.\nVous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    'Go to Login': 'Aller à la connexion',
    'Link Expired': 'Lien expiré',
    'This reset link has expired or was already used.\nPlease request a new one.': 'Ce lien de réinitialisation a expiré ou a déjà été utilisé.\nVeuillez en demander un nouveau.',
    'Request New Link': 'Demander un nouveau lien',
    'Set New Password': 'Définir un nouveau mot de passe',
    'Choose a strong new password for your account.': 'Choisissez un nouveau mot de passe fort pour votre compte.',
    'New Password': 'Nouveau mot de passe',
    'At least 8 characters': 'Au moins 8 caractères',
    'Reset Password': 'Réinitialiser le mot de passe',
    'Minimum 8 characters': 'Minimum 8 caractères',
    'Must include an uppercase letter': 'Doit inclure une lettre majuscule',
    'Must include a number': 'Doit inclure un chiffre',
    'Invalid or missing reset token. Please request a new link.': 'Jeton de réinitialisation invalide ou manquant. Veuillez demander un nouveau lien.',
    'Reset failed. The link may have expired.': 'La réinitialisation a échoué. Le lien a peut-être expiré.',
    'Email Verified!': 'E-mail vérifié !',
    'Your email address has been verified successfully.\nYou can now log in to your account and enjoy GlUnity.': 'Votre adresse e-mail a été vérifiée avec succès.\nVous pouvez maintenant vous connecter à votre compte et profiter de GlUnity.',
    'Verification Failed': 'Échec de la vérification',
    'This verification link is invalid or has expired.\nPlease request a new verification email.': 'Ce lien de vérification est invalide ou a expiré.\nVeuillez demander un nouvel e-mail de vérification.',
    'Resend Verification': 'Renvoyer la vérification',

    // SplashScreen
    'Glutenia logo': 'GlUnity',
    'Sans Gluten, Sans probleme': 'Sans Gluten, Sans problème',

    // Product details
    'About this product': 'À propos de ce produit',
    'Ingredients': 'Ingrédients',
    'Price': 'Prix',
    'View Seller': 'Voir le vendeur',
    '2.4 km away': 'à 2,4 km',
    'Open today • 08:00 - 19:00': 'Ouvert aujourd\'hui • 08:00 - 19:00',
    'A rustic gluten-free loaf with a crispy crust and chewy interior. Fermented for 24 hours for optimal flavor and digestion.': 'Un pain rustique sans gluten avec une croûte croustillante et une mie moelleuse. Fermenté pendant 24 heures pour une saveur et une digestion optimales.',
    'Delicate gluten-free pastry made with certified safe flours. Perfectly layered and baked to a golden finish.': 'Pâtisserie délicate sans gluten à base de farines certifiées sûres. Parfaitement feuilletée et dorée.',
    'Soft, fluffy gluten-free bread baked fresh every morning. Made from 100% certified gluten-free grains.': 'Pain sans gluten doux et moelleux cuit frais tous les matins. Fait de grains 100% certifiés sans gluten.',
    'Premium gluten-free flour blend, perfect for home baking. Contains no traces of wheat, rye, or barley.': 'Mélange de farine sans gluten de qualité supérieure, idéal pour la cuisson maison. Sans traces de blé, de seigle ou d\'orge.',
    'Light and crunchy gluten-free snack, ideal for people with celiac disease or gluten intolerance.': 'En-cas sans gluten léger et croustillant, idéal pour les personnes atteintes de la maladie cœliaque ou d\'intolérance au gluten.',
    'Indulgent gluten-free dessert crafted with the finest safe ingredients. Satisfying and totally wheat-free.': 'Dessert sans gluten gourmand préparé avec les meilleurs ingrédients sûrs. Savoureux et totalement sans blé.',
    'Lovingly crafted at home using traditional recipes adapted for gluten-free diets. Made with natural ingredients.': 'Confectionné avec amour à la maison selon des recettes traditionnelles adaptées au régime sans gluten. Fait d\'ingrédients naturels.',
    'A premium gluten-free product crafted with certified ingredients, safe for people with celiac disease and gluten intolerance.': 'Un produit de qualité supérieure sans gluten fabriqué avec des ingrédients certifiés, sûr pour les cœliaques et les intolérants.',

    // Patient Resources categories
    'Celiac\nDisease': 'Maladie\nCœliaque',
    'Diet Basics': 'Bases du régime',
    'Safe Foods\n& Risks': 'Aliments sûrs\n& Risques',
    'Lifestyle\nTips': 'Conseils de\nvie',
    'min read': 'min de lecture',
    'min': 'min',
    'Read more': 'Lire la suite',
    'Read more →': 'Lire la suite →',
    'All ressources': 'Toutes les ressources',
    'No resources found': 'Aucune ressource trouvée',
    'Videos & Sessions': 'Vidéos & Sessions',
    'See All': 'Voir tout',
    'This content is for informational purposes only and does not replace professional medical advice. Always consult a healthcare provider.': 'Ce contenu est fourni à titre informatif uniquement et ne remplace pas un avis médical professionnel. Consultez toujours un professionnel de la santé.',

    // Patient Resources seed articles
    'What is Celiac Disease?': 'Qu\'est-ce que la maladie cœliaque ?',
    'A comprehensive guide to understanding celiac disease, its symptoms, diagnosis,': 'Un guide complet pour comprendre la maladie cœliaque, ses symptômes, son diagnostic,',
    'Celiac disease is a serious autoimmune disorder that occurs in genetically predisposed people where the ingestion of gluten leads to damage in the small intestine. Learn about symptoms, diagnosis, and living gluten-free.': 'La maladie cœliaque est une maladie auto-immune grave qui survient chez les personnes génétiquement prédisposées, où l\'ingestion de gluten endommage l\'intestin grêle. Découvrez les symptômes, le diagnostic et la vie sans gluten.',
    'Dr. Amira Ben Ali': 'Dr Amira Ben Ali',
    'Starting a Gluten-Free Diet': 'Commencer un régime sans gluten',
    'Essential steps and practical advice for patients transitioning to a gluten-free': 'Étapes essentielles et conseils pratiques pour les patients en transition vers le sans gluten',
    'Transitioning to a gluten-free diet requires careful planning and education. This guide covers what foods to avoid, safe alternatives, and how to read labels.': 'La transition vers un régime sans gluten nécessite une planification et une éducation minutieuses. Ce guide couvre les aliments à éviter, les alternatives sûres et la lecture des étiquettes.',
    'Nutritionist Panel': 'Comité de nutritionnistes',
    'Hidden Sources of Gluten': 'Sources cachées de gluten',
    'Gluten hides in many unexpected products including sauces, medications, and cosmetics. Learn to identify and avoid these hidden sources to stay safe.': 'Le gluten se cache dans de nombreux produits inattendus, notamment les sauces, les médicaments et les cosmétiques. Apprenez à identifier et éviter ces sources cachées pour rester en sécurité.',
    'GlUnity Medical Team': 'Équipe médicale GlUnity',
    'Nutritional Deficiencies in Celiac Patients': 'Déficiences nutritionnelles chez les cœliaques',
    'Celiac disease can lead to deficiencies in iron, folate, calcium, and vitamins B12 and D. This article explains how to identify and address these deficiencies.': 'La maladie cœliaque peut entraîner des carences en fer, folate, calcium et vitamines B12 et D. Cet article explique comment identifier et traiter ces carences.',
    'Dining Out Safely': 'Manger à l\'extérieur en toute sécurité',
    'Eating out with celiac disease requires preparation and communication. This guide teaches you how to ask the right questions and choose safe restaurants.': 'Manger à l\'extérieur avec la maladie cœliaque nécessite de la préparation et de la communication. Ce guide vous apprend à poser les bonnes questions et à choisir des restaurants sûrs.',
    'Living with Celiac Disease': 'Vivre avec la maladie cœliaque',
    'Gluten-Free Meal Prep': 'Préparation de repas sans gluten',
    'by': 'par',
    'Article': 'Article',
    'Video': 'Vidéo',

    // Map screen
    'Filter places': 'Filtrer les lieux',
    'Category': 'Catégorie',
    'Status': 'Statut',
    'Certified only': 'Certifié uniquement',
    'Gluten-free only': 'Sans gluten uniquement',
    'Clear filters': 'Effacer les filtres',
    'Get in Touch': 'Contactez-nous',
    'No phone number listed': 'Aucun numéro répertorié',
    'Copied!': 'Copié !',
    'Copy Number': 'Copier le numéro',
    'Call Now': 'Appeler maintenant',
    'Cancel': 'Annuler',
    'Filter': 'Filtrer',
    'reviews': 'avis',
    'KM': 'KM',
    'Read More': 'Lire plus',
    '({reviewLabel} reviews)': '({reviewLabel} avis)',
    '{distance} km away from you': 'à {distance} km de vous',
    'Gluten Free': 'Sans Gluten',

    // Map categories
    'All': 'Tout',
    'Restaurants': 'Restaurants',
    'Bakeries': 'Boulangeries',
    'Grocery': 'Épicerie',
    'Cafés': 'Cafés',
    'Pharmacy': 'Pharmacie',

    // Map seed locations
    'Ben Yaghlane Shops': 'Boutiques Ben Yaghlane',
    'Premium Tunisian grocery known for high-end gluten-free pasta, breads and gourmet products.': 'Épicerie tunisienne de qualité réputée pour ses pâtes, pains et produits gourmets sans gluten haut de gamme.',
    'Avenue Habib Bourguiba': 'Avenue Habib Bourguiba',
    'Tunis': 'Tunis',
    'La Maison Sans Gluten': 'La Maison Sans Gluten',
    'Dedicated 100% gluten-free bakery with fresh breads and pastries daily.': 'Boulangerie dédiée 100 % sans gluten avec pains et pâtisseries fraîches tous les jours.',
    '14 Rue de Marseille': '14 Rue de Marseille',
    'Green Leaf Café': 'Green Leaf Café',
    'Cozy café offering certified gluten-free brunch, salads and smoothies.': 'Café chaleureux proposant brunchs, salades et smoothies certifiés sans gluten.',
    'Avenue Mohamed V': 'Avenue Mohamed V',
    'Pasta Verde': 'Pasta Verde',
    'Italian restaurant with a separate gluten-free kitchen line.': 'Restaurant italien avec une ligne de cuisine sans gluten séparée.',
    '5 Rue de Carthage': '5 Rue de Carthage',
    'Carrefour Marsa': 'Carrefour Marsa',
    'Supermarket with a wide selection of gluten-free products. Some shared shelves — check labels.': 'Supermarché avec une large sélection de produits sans gluten. Étagères partagées - vérifiez les étiquettes.',
    'La Marsa': 'La Marsa',
    'Pharmacie Centrale': 'Pharmacie Centrale',
    'Stocks specialized gluten-free dietary supplements and medical-grade products.': 'Propose des compléments alimentaires spécialisés sans gluten et des produits de qualité médicale.',
    'Rue Charles de Gaulle': 'Rue Charles de Gaulle',
  },
  ar: {
    // Nav & Headers
    Home: 'الرئيسية',
    Events: 'الأحداث',
    Reels: 'مقاطع',
    Profile: 'الملف الشخصي',
    Welcome: 'مرحبًا',
    Recipes: 'وصفات',
    Map: 'الخريطة',
    'Patient Resources': 'مصادر المرضى',
    Notifications: 'الإشعارات',
    Settings: 'الإعدادات',
    'Edit Profile': 'تعديل الملف الشخصي',
    'Add Event': 'إضافة حدث',
    Community: 'المجتمع',

    // Section Labels
    ACCOUNT: 'الحساب',
    NOTIFICATIONS: 'الإشعارات',
    APPEARANCE: 'المظهر',
    SUPPORT: 'الدعم',

    // Setting Items & Subtitles
    EDIT_PROFILE: 'تعديل الملف الشخصي',
    EDIT_PROFILE_SUB: 'تحديث الاسم، الصورة والمعلومات',
    CHANGE_PASSWORD: 'تغيير كلمة المرور',
    CHANGE_PASSWORD_SUB: 'تحديث بيانات تسجيل الدخول',
    PUSH_NOTIFS: 'إشعارات الهاتف',
    PUSH_NOTIFS_SUB: 'التنبيهات، التذكيرات والتحديثات',
    EMAIL_UPDATES: 'تحديثات البريد الإلكتروني',
    EMAIL_UPDATES_SUB: 'الملخص الأسبوعي والنشرات الإخبارية',
    DARK_MODE: 'الوضع الداكن',
    DARK_MODE_SUB: 'التبديل إلى المظهر الداكن',
    TEXT_SIZE: 'حجم الخط',
    LANGUAGE: 'اللغة',
    LANGUAGE_SUB: 'اختر لغتك المفضلة',
    HELP_CENTER: 'مركز المساعدة',
    HELP_CENTER_SUB: 'الأسئلة الشائعة والأدلة',
    REPORT_BUG: 'الإبلاغ عن مشكلة',
    REPORT_BUG_SUB: 'ساعدنا في تحسين التطبيق',

    // General Actions & Dialogs
    LOGOUT: 'تسجيل الخروج',
    CLOSE: 'إغلاق',
    CANCEL: 'إلغاء',
    SUBMIT: 'إرسال',
    SAVE: 'حفظ',
    SUCCESS: 'نجاح',
    ERROR: 'خطأ',
    'Log out': 'تسجيل الخروج',
    'Privacy & Security': 'الخصوصية والأمان',

    // Welcome Screen
    'Salut , Bienvenue!': 'مرحبًا بك!',
    'Connectez-vous\npour continuer': 'سجل الدخول\nللمتابعة',
    'Se connecter': 'تسجيل الدخول',
    'Creer un compte': 'إنشاء حساب',

    // Auth Screens
    Login: 'تسجيل الدخول',
    LOGIN: 'تسجيل الدخول',
    REGISTER: 'تسجيل',
    'GET STARTED': 'ابدأ الآن',
    'Full Name': 'الاسم الكامل',
    'Enter your name': 'أدخل اسمك الكامل',
    Email: 'البريد الإلكتروني',
    'Enter your email': 'أدخل بريدك الإلكتروني',
    Password: 'كلمة المرور',
    'Enter your password': 'أدخل كلمة المرور',
    'Create a password': 'أنشئ كلمة مرور',
    'Confirm Password': 'تأكيد كلمة المرور',
    'Re-enter your password': 'أعد إدخال كلمة المرور',
    'Forgot Password?': 'هل نسيت كلمة المرور؟',
    'Already Account? ': 'لديك حساب بالفعل؟ ',
    'No Account? ': 'ليس لديك حساب؟ ',
    Register: 'سجل الآن',
    'Profile Type': 'نوع الحساب',
    'Min 8 chars · one uppercase · one number': '8 أحرف كحد أدنى · حرف كبير · رقم واحد',
    Celiac: 'سيلياك',
    Proche: 'قريب',
    'Pro Commerce': 'حساب تجاري',
    'Pro Health': 'حساب صحي',

    // Form errors
    'Email is required': 'البريد الإلكتروني مطلوب',
    'Invalid email': 'البريد الإلكتروني غير صالح',
    'Password is required': 'كلمة المرور مطلوبة',
    'Full name must be at least 2 characters': 'يجب أن يكون الاسم الكامل حرفين على الأقل',
    'Valid email is required': 'يرجى إدخال بريد إلكتروني صالح',
    'Password must be at least 8 characters': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    'Must contain an uppercase letter': 'يجب أن تحتوي على حرف كبير',
    'Must contain a number': 'يجب أن تحتوي على رقم',
    'Passwords do not match': 'كلمات المرور غير متطابقة',
    'Please select a profile type': 'يرجى اختيار نوع الحساب',

    // Change Password Modal
    CURRENT_PASSWORD: 'كلمة المرور الحالية',
    NEW_PASSWORD: 'كلمة المرور الجديدة',
    CONFIRM_PASSWORD: 'تأكيد كلمة المرور الجديدة',
    ENTER_CURRENT_PWD: 'أدخل كلمة المرور الحالية',
    ENTER_NEW_PWD: 'أدخل كلمة المرور الجديدة',
    CONFIRM_NEW_PWD: 'تأكيد كلمة المرور الجديدة',
    REQ_FIELDS: 'جميع الحقول مطلوبة.',
    PWD_LENGTH: 'يجب أن تكون كلمة المرور الجديدة 6 أحرف على الأقل.',
    PWD_MATCH: 'كلمات المرور الجديدة غير متطابقة.',
    PWD_SUCCESS: 'تم تحديث كلمة المرور بنجاح! ✅',
    PWD_FAIL: 'فشل تغيير كلمة المرور. يرجى التحقق من كلمة المرور الحالية.',

    // Report Bug Modal
    BUG_TITLE: 'عنوان المشكلة',
    BUG_DESC: 'وصف المشكلة',
    SEVERITY: 'الأهمية',
    SUBMIT_REPORT: 'إرسال التقرير',
    THANK_YOU: 'شكرًا لك! ✅',
    BUG_SUBMITTED: 'تم إرسال تقريرك بنجاح.',
    LOW: 'منخفض',
    MEDIUM: 'متوسط',
    HIGH: 'مرتفع',
    FIELDS_REQ: 'الحقول مطلوبة',
    ENTER_BUG_DETAILS: 'يرجى إدخال عنوان ووصف للمشكلة.',
    SUBMIT_ERROR: 'خطأ في الإرسال',
    BUG_FAIL_TEXT: 'فشل الإبلاغ عن المشكلة. يرجى المحاولة مرة أخرى.',
    BUG_TITLE_PLACEHOLDER: 'مثال: يتوقف التطبيق عند البحث',
    BUG_DESC_PLACEHOLDER: 'أخبرنا بما حدث بالتفصيل...',

    // Text Size Modal
    SMALL: 'صغير',
    MEDIUM_SIZE: 'متوسط',
    LARGE: 'كبير',

    // Language Modal
    SELECT_LANGUAGE: 'اختر اللغة',
    ENGLISH: 'الإنجليزية',
    FRENCH: 'الفرنسية',
    ARABIC: 'العربية',

    // FAQs
    FAQ_Q1: 'كيف أعرف أن المنتج خالٍ من الغلوتين؟',
    FAQ_A1: 'جميع المنتجات المعروضة على GlUnity معتمدة كخالية من الغلوتين من قبل شركائنا البائعين. ابحث عن شارة "GF" في قائمة المنتجات، أو تحقق من حالة التوصية للمخبز نفسه.',
    FAQ_Q2: 'كيف يمكنني الاتصال بالبائع؟',
    FAQ_A2: 'يمكنك الضغط على زر "عرض البائع" في صفحة تفاصيل المنتج لعرض ملفه الشخصي، حيث يمكنك الاتصال به مباشرة أو إرسال رسالة.',
    FAQ_Q3: 'ما هو المخبز الموصى به من Glutenia؟',
    FAQ_A3: 'هو مخبز تم التحقق منه من قبل فرق السلامة الطبية والغذائية لدينا لضمان إنتاج خالٍ بنسبة 100% من التلوث المتبادل، وآمن لمرضى السيلياك.',
    FAQ_Q4: 'كيف يمكنني تغيير تفضيلات اللغة الخاصة بي؟',
    FAQ_A4: 'يمكنك تحديث لغتك في صفحة الإعدادات تحت قسم الدعم.',

    // Home Screen Text
    'Instantly Check for Gluten & Find Safe Alternatives': 'تحقق فورًا من الغلوتين وابحث عن بدائل آمنة',
    'Tap to Scan': 'اضغط للمسح الضوئي',
    'Quick Access': 'الوصول السريع',
    'Check recipes': 'تصفح الوصفات',
    'Check Events': 'تصفح الأحداث',
    'See All': 'عرض الكل',
    'Find Products': 'البحث عن منتجات',
    'Search products, recipes, events': 'البحث عن منتجات، وصفات، أحداث',
    'Gluten-Free Recipes': 'وصفات خالية من الغلوتين',
    'Healthy and nutritious food recipes': 'وصفات طعام صحية ومغذية',
    'Popular recipes': 'الوصفات الشائعة',
    Popular: 'شائع',
    recipes: 'وصفات',

    // Recipes & details
    Ingredients: 'المكونات',
    Steps: 'الخطوات',
    Nutrition: 'القيمة الغذائية',
    Calories: 'سعرة حرارية',
    Carbs: 'كربوهيدرات',
    Protein: 'بروتين',

    // Events Screen Text
    All: 'الكل',
    Meetups: 'تجمعات',
    Classes: 'دروس',
    Markets: 'أسواق',
    'Aucun événement à afficher.': 'لا توجد أحداث لعرضها.',

    // Patient Resources
    Categories: 'الفئات',
    Featured: 'مميز',
    'All ressources': 'كل المصادر',
    'Videos & Sessions': 'فيديو وجلسات',
    'No resources found': 'لم يتم العثور على مصادر',
    'Read more': 'اقرأ المزيد',
    'Read more →': 'اقرأ المزيد ←',
    'min read': 'دقائق للقراءة',
    min: 'دقيقة',
    'This content is for informational purposes only and does not replace professional medical advice. Always consult a healthcare provider.': 'هذا المحتوى لأغراض إعلامية فقط ولا يغني عن الاستشارة الطبية المهنية. استشر دائمًا مقدم الرعاية الصحية.',
    'Celiac\nDisease': 'مرض\nالسيلياك',
    'Diet Basics': 'أساسيات\nالحمية',
    'Safe Foods\n& Risks': 'الأطعمة الآمنة\nوالمخاطر',
    'Lifestyle\nTips': 'نصائح\nنمط الحياة',

    // Profile Screen
    'Your Role': 'دورك',
    'Your Journey': 'مسيرتك',
    'Every action makes the ecosystem stronger.': 'كل عمل يجعل النظام البيئي أقوى.',
    Beginner: 'مبتدئ',
    Aware: 'مدرك',
    'Safe Eater': 'آكل آمن',
    Fighter: 'مقاتل',
    Titan: 'عملاق',
    'Gluten-Free Warrior': 'محارب خالي من الغلوتين',
    'Living gluten-free for 12 years 🌿': 'يعيش بدون غلوتين منذ 12 عامًا 🌿',
    'You actively manage your gluten-free lifestyle and inspire others.': 'أنت تدير نمط حياتك الخالي من الغلوتين بنشاط وتلهم الآخرين.',

    // Mock Data Translates
    'Gluten-Free Pizza': 'بيتزا خالية من الغلوتين',
    'Homemade GF crust topped with fresh mozzarella and basil.': 'عجينة بيتزا محلية الصنع خالية من الغلوتين مغطاة بالجبن والريحان.',
    'Tunisian Brik': 'بريك تونسي',
    'Crispy gluten-free pastry filled with egg, tuna, and parsley.': 'عجينة بريك مقرمشة خالية من الغلوتين محشوة بالبيض، التونة والبقدونس.',
    'Quinoa Salad': 'سلطة الكينوا',
    'Refreshing salad with quinoa, cucumber, tomatoes, and lemon dressing.': 'سلطة الكينوا المنعشة مع الخيار والطماطم وعصير الليمون.',
    'Protein GF Pancakes': 'بان كيك بروتين خالي من الغلوتين',
    'Healthy Quinoa Bowl': 'وعاء الكينوا الصحي',
    'Celiac Disease Basics': 'أساسيات مرض السيلياك',
    'How to Avoid Cross-Contamination': 'كيفية تجنب التلوث المتبادل',
    'Gluten-Free Flour Guide': 'دليل الدقيق الخالي من الغلوتين',
    'Handling Social Dining': 'التعامل مع تناول الطعام الاجتماعي',
    'Celiac Disease: What Is It?': 'مرض السيلياك: ما هو؟',
    'How to Safely Eat Out': 'كيفية تناول الطعام بالخارج بأمان',
    'Hidden Gluten in Everyday Foods': 'الغلوتين الخفي في الأطعمة اليومية',
    'Glutenia recommended': 'موصى به من Glutenia',
    'Verifié par l\'association': 'تم التحقق منه من قبل الجمعية',
    'Gluten-Free cooking class': 'درس طهي خالي من الغلوتين',
    'Celiac Association Meetup': 'تجمع جمعية السيلياك',
    'Gluten-Free Food Market': 'سوق المنتجات الخالية من الغلوتين',
    // Events
    'View on Map': 'عرض على الخريطة',
    'people going': 'أشخاص ذاهبون',
    'About Event': 'حول الحدث',
    'No description provided.': 'لا يوجد وصف للحدث.',
    'Price': 'السعر',
    'Free': 'مجاني',
    'Join Event': 'الانضمام للحدث',
    'Cancel': 'إلغاء',
    'Loading...': 'جاري التحميل...',
    'Cancel participation': 'إلغاء المشاركة',
    'Are you sure you want to cancel your participation? This will remove you from the attendee list.': 'هل أنت متأكد من إلغاء مشاركتك؟ سيتم إزالتك من قائمة الحضور.',
    'Keep': 'الاحتفاظ',
    // Add Event Screen
    'Organize Event': 'تنظيم حدث',
    'Event Title *': 'عنوان الحدث *',
    'Starts At *': 'يبدأ في *',
    'Venue Name': 'اسم المكان',
    'Street Address': 'عنوان الشارع',
    'City': 'المدينة',
    'Country': 'البلد',
    'Max Capacity': 'العدد الأقصى للحضور',
    'Price (TND)': 'السعر (د.ت)',
    'About the Event': 'عن الحدث',
    'Create Event': 'إنشاء حدث',
    'Add Cover Photo': 'إضافة صورة غلاف',
    'Recommend landscape 16:9 ratio': 'يفضل نسبة عرض إلى ارتفاع 16:9',
    'e.g. Gluten-Free Cooking Workshop': 'مثال: ورشة طهي خالية من الغلوتين',
    'Discard draft?': 'تجاهل المسودة؟',
    'You have unsaved changes. Are you sure you want to discard them and leave?': 'لديك تغييرات غير محفوظة. هل أنت متأكد من تجاهلها والمغادرة؟',
    'Keep Editing': 'مواصلة التعديل',
    'Discard': 'تجاهل',
    'Event Created!': 'تم إنشاء الحدث!',
    'Your gluten-free event is now published and visible to the community.': 'تم نشر حدثك الخالي من الغلوتين وهو مرئي الآن للمجتمع.',
    'Go to Calendar': 'الذهاب إلى التقويم',
    // Seller Journey & Info
    'Learner': 'متعلم',
    'Supporter': 'داعم',
    'Advocate': 'مدافع',
    'Champion': 'بطل',
    'Guardian': 'حارس',
    'Gluten-Free Ally': 'حليف خال من الغلوتين',
    'You support and help someone living gluten-free.': 'أنت تدعم وتساعد شخصًا يعيش بدون غلوتين.',
    'My products': 'منتجاتي',
    'Visibility': 'الظهور',
    'Clients messages': 'رسائل العملاء',
    // Alerts/Notifications Screen
    'Mark all': 'قراءة الكل',
    'All caught up! 🌿': 'لقد قرأت كل شيء! 🌿',
    'No new notifications at the moment.': 'لا توجد إشعارات جديدة في الوقت الحالي.',
    // Notification list dynamic text
    'Welcome to GlUnity! 🌾': 'مرحبًا بك في جلونيتي! 🌾',
    'Find certified gluten-free products, local events, and recipes tailored to your lifestyle.': 'اعثر على منتجات خالية من الغلوتين، أحداث محلية، ووصفات مخصصة لنمط حياتك.',
    'Gluten-Free Cooking Workshop 🥞': 'ورشة عمل طهي خالية من الغلوتين 🥞',
    'A new event was published: Pancake Sunday Meetup on June 15th! RSVP to book your spot.': 'تم نشر حدث جديد: تجمع الأحد لطهي الفطائر في 15 جوان! يرجى تأكيد الحضور لحجز مكانك.',
    'Pure Treats Bakery 🥐': 'مخبز Pure Treats 🥐',
    'Senda added fresh gluten-free chocolate croissants to the products market catalog.': 'أضافت سندة كرواسون شوكولاتة طازج وخالٍ من الغلوتين إلى كتالوج السوق.',
    'Community Verified Badge Alert 🛡️': 'تنبيه شارة التحقق من المجتمع 🛡️',
    'Your profile has been verified as a Gluten-Free Warrior! Enjoy our certified badges.': 'تم التحقق من ملفك الشخصي كـ محارب خالي من الغلوتين! استمتع بشاراتنا المعتمدة.',
    // Stats & Seller Dashboard
    'Last 7 days': 'آخر 7 أيام',
    'Last 30 days': 'آخر 30 يومًا',
    'Your visibility': 'مستوى ظهورك',
    'Views': 'المشاهدات',
    'This month': 'هذا الشهر',
    'Reviews': 'التقييمات',
    'Average rating': 'متوسط التقييم',
    'Map clicks': 'نقرات الخريطة',
    'Visits generated': 'الزيارات الناتجة',
    'Products': 'المنتجات',
    'Listed items': 'المعروضات',
    'Views over time': 'المشاهدات بمرور الوقت',
    'Insights': 'رؤى وإحصاءات',
    'Your most viewed product': 'المنتج الأكثر مشاهدة',
    'Almond Croissant': 'كرواسون باللوز',
    'Top user interaction day': 'يوم ذروة التفاعل',
    'Saturday (Peak at 11 AM)': 'السبت (الذروة 11 صباحاً)',
    'Mon': 'الاثنين',
    'Wed': 'الأربعاء',
    'Fri': 'الجمعة',
    'Sun': 'الأحد',
    // Event Categories & Details
    'Meetup': 'تجمع',
    'Class': 'درس',
    'Webinar': 'ندوة عبر الإنترنت',
    'Market': 'سوق',
    'Other': 'آخر',
    // Seller Profile Screen Additional
    '100% Gluten-Free Bakery': 'مخبز خالٍ من الغلوتين بنسبة 100%',
    'Recommended by Glutenia': 'موصى به من قبل Glutenia',
    'Verified safe establishment': 'منشأة معتمدة آمنة',
    '2.4 km away': 'على بعد 2.4 كم',
    'Open today • 08:00 - 19:00': 'مفتوح اليوم • 08:00 - 19:00',
    'Follow': 'متابعة',
    'Message': 'مراسلة',
    'Edit Info': 'تعديل المعلومات',
    'Add': 'إضافة',
    'Product': 'منتج',
    'Dashboard': 'لوحة التحكم',
    'Bakery Menu': 'قائمة المخبز',
    'See all': 'عرض الكل',
    'No products in the menu yet.': 'لا توجد منتجات في القائمة بعد.',
    'Recent Reviews': 'المراجعات الأخيرة',
    'The gluten-free croissants are absolutely wonderful! Best bakery in Tunis.': 'كرواسون خالٍ من الغلوتين رائع للغاية! أفضل مخبز في تونس.',
    "100% safe for celiac. Their bread doesn't crumble at all! Highly recommend.": 'آمن 100% لمرضى السيلياك. خبزهم لا يتفتت على الإطلاق! نوصي به بشدة.',
    'Very tasty treats and friendly staff. Love the Tunis branch.': 'حلويات لذيذة للغاية وموظفون ودودون. أحب فرع تونس.',
    '2 hours ago': 'منذ ساعتين',
    'Yesterday': 'أمس',
    '3 days ago': 'منذ 3 أيام',
    // Product Market Screen
    'Gluten free products': 'منتجات خالية من الغلوتين',
    'homemade': 'منزلي الصنع',
    'Certified': 'معتمد',
    'No products found': 'لم يتم العثور على منتجات',
    'Try a different filter or check back later.': 'جرب تصفية مختلفة أو تحقق لاحقًا.',
    // Recipes Screen
    'Gluten-Free Recipes': 'وصفات خالية من الغلوتين',
    'Healthy and nutritious food recipes': 'وصفات طعام صحية ومغذية',
    'Popular': 'شائع',
    'recipes': 'الوصفات',
    'Tunisian': 'تونسي',
    'Easy': 'سهل',
    'Quick': 'سريع',
    // Customer Profile Screen
    'Gluten-Free Warrior': 'محارب خالي من الغلوتين',
    'Living gluten-free for 12 years 🌿': 'أعيش حياة خالية من الغلوتين منذ 12 عاماً 🌿',
    'Your Role': 'دورك',
    'You actively manage your gluten-free lifestyle and inspire others.': 'أنت تدير بنشاط نمط حياتك الخالي من الغلوتين وتلهم الآخرين.',
    'Your Journey': 'رحلتك',
    'Beginner': 'مبتدئ',
    'Aware': 'واعٍ',
    'Safe Eater': 'آكل آمن',
    'Fighter': 'مقاتل',
    'Titan': 'عملاق',
    'Every action makes the ecosystem stronger.': 'كل عمل يجعل النظام البيئي أقوى.',
    'Privacy & Security': 'الخصوصية والأمان',
    'Log out': 'تسجيل الخروج',

    // Map Screen AR
    'Filter places': 'تصفية الأماكن',
    'Category': 'الفئة',
    'Status': 'الحالة',
    'Certified only': 'المعتمدة فقط',
    'Gluten-free only': 'الخالية من الغلوتين فقط',
    'Clear filters': 'مسح الفلاتر',
    'Get in Touch': 'تواصل معنا',
    'No phone number listed': 'لا يوجد رقم هاتف مدرج',
    'Copied!': 'تم النسخ!',
    'Copy Number': 'نسخ الرقم',
    'Call Now': 'اتصل الآن',
    Restaurants: 'مطاعم',
    Bakeries: 'مخابز',
    Grocery: 'بقالة',
    'Cafés': 'مقاهي',
    Pharmacy: 'صيدليات',

    // Events search & empty state
    'Search events...': 'البحث في الفعاليات...',
    'No events to display.': 'لا توجد فعاليات لعرضها.',

    // BottomNavBar accessibility
    'Scan for gluten': 'فحص الغلوتين',

    // Header greeting
    Welcome: 'مرحباً',

    // Add Event extra fields
    'Event Type': 'نوع الفعالية',
    'Event title is required.': 'عنوان الفعالية مطلوب.',
    'Date format is required (e.g. YYYY-MM-DD).': 'صيغة التاريخ مطلوبة (مثال: YYYY-MM-DD).',
    'Location Details': 'تفاصيل الموقع',
    'e.g. Green Bakery': 'مثال: المخبز الأخضر',
    'e.g. 15 Avenue de Paris': 'مثال: 15 شارع باريس',
    'Tunis': 'تونس',
    'Tunisia': 'تونس',
    'About the event': 'حول الفعالية',

    // Seller Pro Profile (menu items)
    'My products': 'منتجاتي',
    'Clients messages': 'رسائل العملاء',
    Visibility: 'الظهور',

    // Intro / Onboarding
    'Scannez Vos': 'افحص',
    'Aliments': 'طعامك',
    "Scannez rapidement les produits pour vérifier s'ils sont sans gluten et sûrs.": "افحص الباركود بسرعة للتحقق فوراً مما إذا كانت المنتجات خالية من الغلوتين وآمنة لنظامك الغذائي.",
    'Trouvez Des': 'ابحث عن',
    'Lieux Sûrs': 'أماكن آمنة',
    'Découvrez les restaurants, boulangeries et magasins proposant des options sans gluten près de chez vous.': 'اكتشف المطاعم، المخابز ومحلات البقالة المحلية المعتمدة التي تقدم خيارات موثوقة خالية من الغلوتين.',
    'Rejoignez La': 'انضم إلى',
    'Communauté': 'المجتمع',
    "Partagez des recettes, des conseils et des expériences avec d'autres personnes vivant sans gluten.": "شارك الوصفات، اقرأ المقالات، اطرح الأسئلة وتواصل مع محاربي السيلياك الآخرين القريبين منك.",

    // Welcome / Auth Screens
    'Salut , Bienvenue!': 'أهلاً بك، مرحباً!',
    'Connectez-vous\npour continuer': 'سجل الدخول\nللمتابعة',
    'Se connecter': 'تسجيل الدخول',
    'Creer un compte': 'إنشاء حساب',
    'Login': 'تسجيل الدخول',
    'Email': 'البريد الإلكتروني',
    'Enter your email': 'أدخل بريدك الإلكتروني',
    'Password': 'كلمة المرور',
    'Enter your password': 'أدخل كلمة المرور',
    'Forgot Password?': 'هل نسيت كلمة المرور؟',
    'LOGIN': 'تسجيل الدخول',
    'No Account? ': 'ليس لديك حساب؟ ',
    'Register': 'تسجيل حساب جديد',
    'Email is required': 'البريد الإلكتروني مطلوب',
    'Invalid email': 'البريد الإلكتروني غير صالح',
    'Password is required': 'كلمة المرور مطلوبة',
    'GET STARTED': 'ابدأ الآن',
    'Full Name': 'الاسم الكامل',
    'Enter your name': 'أدخل اسمك الكامل',
    'Create a password': 'أنشئ كلمة مرور',
    'Confirm Password': 'تأكيد كلمة المرور',
    'Re-enter your password': 'أعد إدخال كلمة المرور',
    'Profile Type': 'نوع الحساب',
    'Celiac': 'سيلياك',
    'Proche': 'قريب/صديق',
    'Pro Commerce': 'حساب تجاري',
    'Pro Health': 'حساب صحي',
    'Please select a profile type': 'يرجى اختيار نوع الحساب',
    'Min 8 chars · one uppercase · one number': '8 أحرف كحد أدنى · حرف كبير · رقم',
    'REGISTER': 'تسجيل',
    'Already Account? ': 'لديك حساب بالفعل؟ ',
    'Full name must be at least 2 characters': 'الاسم الكامل يجب أن يكون حرفين على الأقل',
    'Valid email is required': 'يرجى إدخال بريد إلكتروني صالح',
    'Password must be at least 8 characters': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    'Must contain an uppercase letter': 'يجب أن تحتوي على حرف كبير',
    'Must contain a number': 'يجب أن تحتوي على رقم',
    'Passwords do not match': 'كلمات المرور غير متطابقة',
    'Forgot Password': 'نسيت كلمة المرور',
    'Please enter a valid email address': 'يرجى إدخال بريد إلكتروني صالح',
    'Submit': 'إرسال',
    '← Back to Login': '← العودة لتسجيل الدخول',
    'Email sent to change your password': 'تم إرسال بريد إلكتروني لتغيير كلمة المرور',
    'Back to Login': 'العودة لتسجيل الدخول',
    'Password Updated!': 'تم تحديث كلمة المرور!',
    'Your password has been reset successfully.\nYou can now log in with your new password.': 'تم إعادة تعيين كلمة المرور بنجاح.\nيمكنك الآن تسجيل الدخول باستخدام كلمة المرور الجديدة.',
    'Go to Login': 'الذهاب لتسجيل الدخول',
    'Link Expired': 'انتهت صلاحية الرابط',
    'This reset link has expired or was already used.\nPlease request a new one.': 'انتهت صلاحية رابط إعادة التعيين هذا أو تم استخدامه بالفعل.\nيرجى طلب رابط جديد.',
    'Request New Link': 'طلب رابط جديد',
    'Set New Password': 'تعيين كلمة مرور جديدة',
    'Choose a strong new password for your account.': 'اختر كلمة مرور جديدة قوية لحسابك.',
    'New Password': 'كلمة مرور جديدة',
    'At least 8 characters': '8 أحرف كحد أدنى',
    'Reset Password': 'إعادة تعيين كلمة المرور',
    'Minimum 8 characters': '8 أحرف كحد أدنى',
    'Must include an uppercase letter': 'يجب أن تشمل حرفاً كبيراً',
    'Must include a number': 'يجب أن تشمل رقماً',
    'Invalid or missing reset token. Please request a new link.': 'رمز إعادة التعيين غير صالح أو مفقود. يرجى طلب رابط جديد.',
    'Reset failed. The link may have expired.': 'فشلت إعادة التعيين. ربما انتهت صلاحية الرابط.',
    'Email Verified!': 'تم التحقق من البريد الإلكتروني!',
    'Your email address has been verified successfully.\nYou can now log in to your account and enjoy GlUnity.': 'تم التحقق من عنوان بريدك الإلكتروني بنجاح.\nيمكنك الآن تسجيل الدخول إلى حسابك والاستمتاع بـ GlUnity.',
    'Verification Failed': 'فشل التحقق',
    'This verification link is invalid or has expired.\nPlease request a new verification email.': 'رابط التحقق هذا غير صالح أو منتهي الصلاحية.\nيرجى طلب بريد إلكتروني جديد للتحقق.',
    'Resend Verification': 'إعادة إرسال التحقق',

    // SplashScreen
    'Glutenia logo': 'جلو-يونيتي',
    'Sans Gluten, Sans probleme': 'خالي من الغلوتين، خالي من المشاكل',

    // Product details
    'About this product': 'حول هذا المنتج',
    'Ingredients': 'المكونات',
    'Price': 'السعر',
    'View Seller': 'عرض البائع',
    '2.4 km away': 'على بعد 2.4 كم',
    'Open today • 08:00 - 19:00': 'مفتوح اليوم • 08:00 - 19:00',
    'A rustic gluten-free loaf with a crispy crust and chewy interior. Fermented for 24 hours for optimal flavor and digestion.': 'رغيف ريفي خالي من الغلوتين مع قشرة مقرمشة ولب طري. مخمر لمدة 24 ساعة للحصول على أفضل نكهة وهضم.',
    'Delicate gluten-free pastry made with certified safe flours. Perfectly layered and baked to a golden finish.': 'فطائر خالية من الغلوتين محضرة بدقيق آمن ومعتمد. طبقات مثالية ومخبوزة حتى اللون الذهبي.',
    'Soft, fluffy gluten-free bread baked fresh every morning. Made from 100% certified gluten-free grains.': 'خبز ناعم وهش خالي من الغلوتين يخبز طازجاً كل صباح. مصنوع من حبوب خالية من الغلوتين معتمدة بنسبة 100%.',
    'Premium gluten-free flour blend, perfect for home baking. Contains no traces of wheat, rye, or barley.': 'خليط دقيق ممتاز خالي من الغلوتين، مثالي للخبز المنزلي. لا يحتوي على أي آثار للقمح أو الشعير.',
    'Light and crunchy gluten-free snack, ideal for people with celiac disease or gluten intolerance.': 'وجبة خفيفة ومقرمشة خالية من الغلوتين، مثالية لمرضى السيلياك أو حساسية الغلوتين.',
    'Indulgent gluten-free dessert crafted with the finest safe ingredients. Satisfying and totally wheat-free.': 'حلوى لذيذة خالية من الغلوتين مصنوعة من أجود المكونات الآمنة. مرضية وخالية تماماً من القمح.',
    'Lovingly crafted at home using traditional recipes adapted for gluten-free diets. Made with natural ingredients.': 'صنع بحب في المنزل باستخدام وصفات تقليدية معدلة للأنظمة الغذائية الخالية من الغلوتين. مصنوع من مكونات طبيعية.',
    'A premium gluten-free product crafted with certified ingredients, safe for people with celiac disease and gluten intolerance.': 'منتج ممتاز خالي من الغلوتين مصنوع من مكونات معتمدة، آمن للأشخاص المصابين بمرض السيلياك وحساسية الغلوتين.',

    // Patient Resources categories
    'Celiac\nDisease': 'مرض\nالسيلياك',
    'Diet Basics': 'أساسيات الحمية',
    'Safe Foods\n& Risks': 'الأطعمة الآمنة\nوالمخاطر',
    'Lifestyle\nTips': 'نصائح\nنمط الحياة',
    'min read': 'دقائق للقراءة',
    'min': 'دقائق',
    'Read more': 'اقرأ المزيد',
    'Read more →': 'اقرأ المزيد ←',
    'All ressources': 'كل المصادر',
    'No resources found': 'لم يتم العثور على مصادر',
    'Videos & Sessions': 'فيديوهات وجلسات',
    'See All': 'عرض الكل',
    'This content is for informational purposes only and does not replace professional medical advice. Always consult a healthcare provider.': 'هذا المحتوى لأغراض إعلامية فقط ولا يغني عن الاستشارة الطبية المهنية. استشر دائماً مقدم الرعاية الصحية.',

    // Patient Resources seed articles
    'What is Celiac Disease?': 'ما هو مرض السيلياك؟',
    'A comprehensive guide to understanding celiac disease, its symptoms, diagnosis,': 'دليل شامل لفهم مرض السيلياك وأعراضه وتشخيصه،',
    'Celiac disease is a serious autoimmune disorder that occurs in genetically predisposed people where the ingestion of gluten leads to damage in the small intestine. Learn about symptoms, diagnosis, and living gluten-free.': 'السيلياك هو اضطران خطير في المناعة الذاتية يحدث لدى الأشخاص المهيئين وراثياً حيث يؤدي تناول الغلوتين إلى تلف الأمعاء الدقيقة. تعرف على الأعراض والتشخيص والعيش خالي من الغلوتين.',
    'Dr. Amira Ben Ali': 'د. أميرة بن علي',
    'Starting a Gluten-Free Diet': 'بدء حمية خالية من الغلوتين',
    'Essential steps and practical advice for patients transitioning to a gluten-free': 'خطوات أساسية ونصائح عملية للمرضى الذين ينتقلون إلى خالي من الغلوتين',
    'Transitioning to a gluten-free diet requires careful planning and education. This guide covers what foods to avoid, safe alternatives, and how to read labels.': 'يتطلب الانتقال إلى نظام غذائي خالي من الغلوتين تخطيطاً وتعليماً دقيقين. يغطي هذا الدليل الأطعمة التي يجب تجنبها والبدائل الآمنة وكيفية قراءة الملصقات.',
    'Nutritionist Panel': 'لجنة خبراء التغذية',
    'Hidden Sources of Gluten': 'مصادر الغلوتين الخفية',
    'Gluten hides in many unexpected products including sauces, medications, and cosmetics. Learn to identify and avoid these hidden sources to stay safe.': 'يختبئ الغلوتين في العديد من المنتجات غير المتوقعة بما في ذلك الصلصات والأدوية ومستحضرات التجميل. تعلم كيفية تحديد هذه المصادر وتجنبها للبقاء آمناً.',
    'GlUnity Medical Team': 'طاقم جلو-يونيتي الطبي',
    'Nutritional Deficiencies in Celiac Patients': 'نقص التغذية لدى مرضى السيلياك',
    'Celiac disease can lead to deficiencies in iron, folate, calcium, and vitamins B12 and D. This article explains how to identify and address these deficiencies.': 'يمكن أن يؤدي مرض السيلياك إلى نقص في الحديد وحمض الفوليك والكالسيوم وفيتامينات B12 وD. تشرح هذه المقالة كيفية تحديد هذا النقص ومعالجته.',
    'Dining Out Safely': 'تناول الطعام في الخارج بأمان',
    'Eating out with celiac disease requires preparation and communication. This guide teaches you how to ask the right questions and choose safe restaurants.': 'يتطلب تناول الطعام في الخارج مع مرض السيلياك الاستعداد والتواصل. يعلمك هذا الدليل كيفية طرح الأسئلة الصحيحة واختيار المطاعم الآمنة.',
    'Living with Celiac Disease': 'التعايش مع مرض السيلياك',
    'Gluten-Free Meal Prep': 'تحضير الوجبات الخالية من الغلوتين',
    'by': 'بواسطة',
    'Article': 'مقال',
    'Video': 'فيديو',

    // Map screen
    'Filter places': 'تصفية الأماكن',
    'Category': 'الفئة',
    'Status': 'الحالة',
    'Certified only': 'المعتمدة فقط',
    'Gluten-free only': 'خالي من الغلوتين فقط',
    'Clear filters': 'مسح التصفية',
    'Get in Touch': 'تواصل معنا',
    'No phone number listed': 'لا يوجد رقم هاتف مدرج',
    'Copied!': 'تم النسخ!',
    'Copy Number': 'نسخ الرقم',
    'Call Now': 'اتصل الآن',
    'Cancel': 'إلغاء',
    'Filter': 'تصفية',
    'reviews': 'تقييمات',
    'KM': 'كم',
    'Read More': 'اقرأ المزيد',
    '({reviewLabel} reviews)': '({reviewLabel} تقييم)',
    '{distance} km away from you': 'على بعد {distance} كم منك',
    'Gluten Free': 'خالي من الغلوتين',

    // Map categories
    'All': 'الكل',
    'Restaurants': 'المطاعم',
    'Bakeries': 'المخابز',
    'Grocery': 'البقالة',
    'Cafés': 'المقاهي',
    'Pharmacy': 'الصيدلية',

    // Map seed locations
    'Ben Yaghlane Shops': 'محلات بن يغلان',
    'Premium Tunisian grocery known for high-end gluten-free pasta, breads and gourmet products.': 'بقالة تونسية متميزة معروفة بالمعكرونة والخبز الفاخر الخالي من الغلوتين والمنتجات الراقية.',
    'Avenue Habib Bourguiba': 'شارع الحبيب بورقيبة',
    'Tunis': 'تونس',
    'La Maison Sans Gluten': 'دار الخالي من الغلوتين',
    'Dedicated 100% gluten-free bakery with fresh breads and pastries daily.': 'مخبز مخصص 100% للخالي من الغلوتين مع خبز ومعجنات طازجة يومياً.',
    '14 Rue de Marseille': '14 نهج مرسيليا',
    'Green Leaf Café': 'مقهى الورقة الخضراء',
    'Cozy café offering certified gluten-free brunch, salads and smoothies.': 'مقهى مريح يقدم وجبات فطور متأخر وسلطات وعصائر معتمدة خالية من الغلوتين.',
    'Avenue Mohamed V': 'شارع محمد الخامس',
    'Pasta Verde': 'باستا فيردي',
    'Italian restaurant with a separate gluten-free kitchen line.': 'مطعم إيطالي مع خط مطبخ منفصل خالي من الغلوتين.',
    '5 Rue de Carthage': '5 نهج قرطاج',
    'Carrefour Marsa': 'كارفور المرسى',
    'Supermarket with a wide selection of gluten-free products. Some shared shelves — check labels.': 'سوبرماركت مع تشكيلة واسعة من المنتجات الخالية من الغلوتين. بعض الرفوف مشتركة - تفقد الملصقات.',
    'La Marsa': 'المرسى',
    'Pharmacie Centrale': 'الصيدلية المركزية',
    'Stocks specialized gluten-free dietary supplements and medical-grade products.': 'توفر المكملات الغذائية المتخصصة الخالية من الغلوتين والمنتجات الطبية.',
    'Rue Charles de Gaulle': 'نهج شارل ديغول',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    async function loadLanguage() {
      try {
        const savedLang = await AsyncStorage.getItem('@pref_language');
        if (savedLang === 'en' || savedLang === 'fr' || savedLang === 'ar') {
          setLanguageState(savedLang);
        }
      } catch (e) {
        console.error('Failed to load language setting:', e);
      }
    }
    loadLanguage();
  }, []);

  const setLanguage = async (lang: LanguageCode) => {
    try {
      await AsyncStorage.setItem('@pref_language', lang);
      setLanguageState(lang);
    } catch (e) {
      console.error('Failed to save language setting:', e);
    }
  };

  const t = (key: string): string => {
    if (!key) return key;
    const cleanKey = key.trim();
    return translations[language]?.[cleanKey] || translations[language]?.[key] || translations['en']?.[cleanKey] || key;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    globalT = t;
    globalIsRTL = isRTL;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
